firebase/firebase-admin-node

- .travis.yml
- test/resources/mocks.ts
- test/unit/auth/auth.spec.ts
- test/unit/firebase.spec.ts
- test/unit/utils/index.spec.ts
The unit test framework requires a local installation of the gcloud SDK, and also to authorize it by running `gcloud auth application-default login`. This is an interactive process which cannot be fully automated. As a result we cannot run it in an automated environment like TravisCI. 
This patch updates application default credential tests to run by setting the `GOOGLE_APPLICATION_CREDENTIALS` environment variable. For a number of other auth tests, we introduce a new `MockCredential` (these tests simply require some non-cert credential).
> Running Unit Tests without gcloud SDK in Automated Environments

- src/utils/validator.ts
- test/unit/utils/validator.spec.ts
Support for handling URLs with `%` signs in path. For example:
`https://test.com/foo%20bar`
Fix for #40
> Supporting % characters in the URL path

- test/integration/index.js
Integration test suite expects default security rules. Therefore it should update the rules accordingly before running tests to avoid false positives.
See #48
> Updating the DB rules to the defaults before running integration tests

- src/utils/api-request.ts
Adding more information to the error message generated at failed HTTP requests.
Useful when debugging issues like #49
> Improving Error Message

- src/auth/auth-api-request.ts
- src/auth/auth.ts
- src/auth/user-record.ts
- src/index.d.ts
- src/utils/error.ts
- src/utils/validator.ts
- test/integration/auth.js
- test/unit/auth/auth-api-request.spec.ts
- test/unit/auth/auth.spec.ts
- test/unit/auth/user-record.spec.ts
- test/unit/utils/validator.spec.ts
Adds phoneNumber to UserRecord and UserInfo.
Implements new API for looking up users by phone number: getUserByPhoneNumber
Adds the ability to pass the phoneNumber property when creating a new user,
or updating an existing one via createUser and updateUser.
This includes the ability to delete the phone number for a specified user.
Defines the new related auth errors:
auth/invalid-phone-number and auth/phone-number-already-exists.
> Implements phone auth support for Admin node.js SDK.

- src/auth/auth-api-request.ts
- src/auth/auth.ts
- src/auth/user-record.ts
- src/index.d.ts
Implementing type definitions for arguments of `createUser()` and `updateUser()` methods in `auth`. This improvement was suggested for the Node SDK during a recent API review discussion. 
@bojeil-google Do we need to send this through the API review process?
See #62.
> Type definitions for createUser() and updateUser() parameters

- createReleaseTarball.sh
- src/index.d.ts
- test/integration/typescript/package.json
- test/integration/typescript/src/example.test.ts
- test/integration/typescript/src/example.ts
- test/integration/typescript/tsconfig.json
- verifyReleaseTarball.sh
This provides a fix for the issue reported in #70. I've taken the easy (and probably safer) way out by dropping the offending import (`Bucket`) altogether, and declaring our API to return `any` instead. I've also added a new `verifyReleaseTarball.sh` script which will check for this type of errors in the future.
Here's the repro of the error as detected by the new verification script:
```npm WARN firebase-admin-typescript-test@1.0.0 No description
npm WARN firebase-admin-typescript-test@1.0.0 No repository field.
npm WARN firebase-admin-typescript-test@1.0.0 No license field.
> tsc -p tsconfig.json
node_modules/firebase-admin/lib/index.d.ts(397,3): error TS2666: Exports and export assignments are not permitted in module augmentations.
Deleted temp working directory /tmp/tmp.fsnUBunSgA …
```
> Fixing a TS compilation error in index.d.ts

- src/auth/token-generator.ts
- src/messaging/messaging.ts
- src/utils/api-request.ts
- test/unit/auth/auth.spec.ts
- test/unit/auth/credential.spec.ts
- test/unit/auth/token-generator.spec.ts
- test/unit/messaging/messaging.spec.ts
Following errors occur when running `gulp`:
```
src/auth/token-generator.ts(159,57): error TS2339: Property 'header' does not exist on type 'string | object'.
Property 'header' does not exist on type 'string'.
src/auth/token-generator.ts(160,58): error TS2339: Property 'payload' does not exist on type 'string | object'.
Property 'payload' does not exist on type 'string'.
src/auth/token-generator.ts(238,26): error TS2339: Property 'uid' does not exist on type 'string | object'.
Property 'uid' does not exist on type 'string'.
src/auth/token-generator.ts(238,45): error TS2339: Property 'sub' does not exist on type 'string | object'.
Property 'sub' does not exist on type 'string'.
src/auth/token-generator.ts(301,50): error TS2339: Property 'split' does not exist on type 'string | string[]'. …
```
> Fixing a number of TS errors/warnings

- .gitignore
- CONTRIBUTING.md
- createReleaseTarball.sh
- gulpfile.js
- package.json
- test/unit/auth/credential.spec.ts
- tsconfig-lint.json
This PR changes how we lint, test and build the SDK.
* Linting: `npm run lint`
* Linting and unit tests: `npm test`
* Unit tests with code coverage: `npm run test:coverage`
* Integration tests: `npm run integration`
With this we will only use gulp when building release packages. Even in that case we can invoke it via npm as `npm run build`. The `createReleaseTarball.sh` script has been updated to use the new npm build targets.
There are couple of advantages to this move:
* The old gulp script was very complicated. This simplifies it down to bare bones.
* Stack traces of failed tests are impossible to comprehend when invoked via gulp (due to compilation and in-memory evaluation of gulp). With this we run mocha directly over TypeScript files, so the line numbers directly map to source code. …
> Updating the build/test/lint scripts to use npm instead of gulp

- src/utils/api-request.ts
- src/utils/error.ts
- test/unit/utils/api-request.spec.ts
In an effort to make the admin SDK more resilient to temporary network errors, this PR adds a single retry to *all* requests made via `HttpRequestHandler` that fail due to a network error.  Timeouts and completed HTTP requests (regardless of response code) will never retry.
To work around #80 this PR also introduces `PrefixedFirebaseError`, a subclass of `FirebaseError` which attempts to make dealing with error-code prefixing a little easier by exposing a `hasCode()` method.
> HttpRequestHandler: Retry on Network Error

- src/index.d.ts
Up until now we have been declaring the return type of `admin.storage().bucket()` to be `any`. We wanted to make it `Bucket`, but ran into issues with it (see #70).
This PR brings the `Bucket` type back into `index.d.ts`, but to avoid errors in downstream applications, we have to also slightly change how we export modules in the type definition file. I'm not sure what the implications of this change are, but at least nothing seems broken (unit tests, integration tests and release verification script are all passing). Feedback welcome.
> Declaring the Bucket return type in index.d.ts

- src/firestore/firestore.ts
- test/integration/index.js
After this fix, we only `require` Firestore conditionally. This means, the SDK won't require `@google-cloud/firestore` until we call `admin.firestore`. In the transpiled JS code, there are 2 instances that require this module. But both of them are now in functions that need to be invoked explicitly:
```
$ grep -r -A 5 -B 5 "require('@google-cloud/firestore')" lib/
lib/firebase-namespace.js-        get: function () {
lib/firebase-namespace.js-            var ns = this;
lib/firebase-namespace.js-            var fn = function (app) {
lib/firebase-namespace.js-                return ns.ensureApp(app).firestore();
lib/firebase-namespace.js-            };
lib/firebase-namespace.js:            return Object.assign(fn, require('@google-cloud/firestore'));
lib/firebase-namespace.js-        }, …
```
> Lazy loading the Firestore implementation

- CONTRIBUTING.md
- createReleaseTarball.sh
- package-lock.json
- package.json
Migrating from `npm-shrinkwrap.json` to `package-lock.json`. This file is far more stable than the shrinkwrap, and it cannot be published with releases. Users who install `firebase-admin` will get the dependencies as stated in our `package.json` file. Package lock also gets automatically updated when we update the `package.json` file.
> Removed skrinkwrap File

- src/index.d.ts
- test/integration/typescript/src/example.test.ts
Adding the old RTDB typings back until we figure out a more permanent solution with the JS SDK. Should resolve issues like #136
> Adding the RTDB typings back

- src/firebase-app.ts
- src/index.d.ts
Since the updates to Firebase Functions (firebase/firebase-functions#127, firebase/firebase-functions#138) ```config()``` function, it seems the ```AppOptions``` type needs to be updated to correctly reflect what keys might be present on the object. I might be missing some (not sure exactly what keys might be present), but I added those that I've used previously (worked previously because ```config().firebase``` used to be of type ```any```).
Only changes to the type definitions.
> Updated types to include potential for other keys in AppOptions.

- package.json
I was trying to integration-test a semver major update, that includes some [breaking changes](https://github.com/google/google-auth-library-nodejs/releases/tag/1.0.0-alpha.1), being made over at [google-auth-library](https://github.com/google/google-auth-library-nodejs). To my surprise, all tests passed. It turns out the package.json is the only thing that depends on `google-auth-library`.
> fix(package): drop unused dep google-auth-library

- test/unit/firestore/firestore.spec.ts
This is to fix some warnings observed in the Travis CI environment (which does not have application default credentials set up).
Before the fix:
```
Firestore
Initializer
✓ should throw given invalid app: null
✓ should throw given invalid app: null
✓ should throw given invalid app: 0
✓ should throw given invalid app: 1
✓ should throw given invalid app: true
✓ should throw given invalid app: false
✓ should throw given invalid app: ""
✓ should throw given invalid app: "a"
✓ should throw given invalid app: []
✓ should throw given invalid app: [1,"a"]
✓ should throw given invalid app: {}
✓ should throw given invalid app: {"a":1}
✓ should throw given invalid app: undefined
✓ should throw given no app
✓ should throw given an invalid credential with project ID
✓ should throw given an invalid …
```
> Fixing some Firestore test warnings, caused by failure to find ADC

- CONTRIBUTING.md
Path typo "test/resource/" -> "test/resources/" .
> Fixing a Path Typo in the Contribution Guide

- test/unit/instance-id/instance-id-request.spec.ts
Using Sinon rejects method to mock failures (Similar to #161).
> Cleaning up IID unit tests

- .travis.yml
Node 8 is the latest stable release of Node.js. And according to #153 Node 5 is no longer supported upstream. Therefore this PR trades Node 5 for 8 in the set of environments tested in CI.
> Added Node 8 to the list of environments we test against

- src/index.d.ts
- test/integration/typescript/src/example.test.ts
Enables TypeScript developers to reference above Firestore types via Admin SDK namespace.
> Exporting DocumentReference and DocumentSnapshot types

- package-lock.json
- src/auth/auth-api-request.ts
- test/integration/auth.spec.ts
Adding a 1 second timeout in the integration tests to make sure revoke happens 1 second after minting. also comment
> Delay promise for revoke

- createReleaseTarball.sh
Replacing the pattern leaves an extra newline character around which has to be removed manually. I'm using a stricter pattern match here (with line delimiters), and then deleting the matched line with sed altogether.
> Removing '# Unreleased' with sed instead of replacing

- src/messaging/messaging.ts
- test/unit/messaging/messaging.spec.ts
The new FCM API does not accept topic names prefixed with `/topics/`. But we can easily check for this in the SDK and remove it. This results in a better and consistent dev experience since the other methods in this API accepts prefixed topic names.
> Accept prefixed topic names

- CHANGELOG.md
- package-lock.json
- package.json
- src/database/database.ts
Related change in JS SDK: https://github.com/firebase/firebase-js-sdk/pull/524
I've verified the correct user-agent header is being passed by adding some log statements to the RTDB client code:
```
{ headers: { 'User-Agent': 'Firebase/5/5.9.0/darwin/AdminNode' } }
```
Resolves #134
> Passing Admin SDK version to RTDB client

- package-lock.json
- package.json
- test/unit/firebase-app.spec.ts
- test/unit/firebase-namespace.spec.ts
Addressing the deprecation warnings:
```
FirebaseApp
#name
✓ should throw if the app has already been deleted
sinon.reset is deprecated and will be removed from the public API in a future version of sinon.
✓ should return the app's name
sinon.reset is deprecated and will be removed from the public API in a future version of sinon.
✓ should be case sensitive
sinon.reset is deprecated and will be removed from the public API in a future version of sinon.
✓ should respect leading and trailing whitespace
sinon.reset is deprecated and will be removed from the public API in a future version of sinon.
✓ should be read-only
sinon.reset is deprecated and will be removed from the public API in a future version of sinon.
#options
✓ should throw if the app has already been deleted
sinon.reset is …
```
> Removing calls to some deprecated Sinon APIs

- .gitignore
- package-lock.json
- src/auth/token-generator.ts
- src/utils/validator.ts
> Using Array.isArray() instead of instanceof

- src/messaging/messaging-api-request.ts
- test/unit/messaging/messaging.spec.ts
Some FCM errors sends a specific error code embedded in the details section of the response:
```
{
"error": {
"code": 404,
"message": "App Instance was uninstalled or unregistered.",
"status": "NOT_FOUND",
"details": [
{
"@type": "type.googleapis.com/google.firebase.fcm.v1.FcmErrorCode",
"errorCode": "UNREGISTERED"
}
]
}
}
```
This PR changes the SDK to use that error code when available.
> Reading FCM error code from the details section

- CHANGELOG.md
- src/index.d.ts
- src/messaging/messaging.ts
- test/unit/messaging/messaging.spec.ts
Explicitly supporting the `mutable-content` option for APNS messages.
```
type Aps = {
mutableContent?: boolean;
[customData]: any;
}
```
> Supporting APNS mutable-content option

- package.json
- src/storage/storage.ts
When initializing a GCS client with a service account credential, we can also specify the `projectId` field. Setting this field is optional, but when specified allows more advanced use cases like creating buckets.
Resolves #261
> Setting the projectId when initializing GCS

- package-lock.json
- src/auth/credential.ts
- src/firebase-app.ts
- src/firebase-namespace.ts
Lazy loading internal modules and some dependencies for faster load times. This essentially defers loading child modules until they are explicitly required (using the technique described [here](http://www.typescriptlang.org/docs/handbook/modules.html#optional-module-loading-and-other-advanced-loading-scenarios)). For example none of the `auth/*` sources will be loaded until `admin.auth()` is invoked. This also ensures that only the child modules used by the developers get loaded into the Node.js process.
Test code:
```
const start = Date.now();
require('firebase-admin');
const end = Date.now();
console.log('Load time:', (end-start), 'ms');
```
Before (ms): 154, 151, 151, 153, 153 (mean = 152.4ms)
After (ms): 18, 18, 17, 18, 18 (mean = 17.8ms)
Speed up of initial load: 88.32%
Before (ms): …
> Lazy loading modules for faster load times

- CHANGELOG.md
- package-lock.json
- package.json
Also removing the redundant dependency on `faye-websocket`. This now comes through `@firebase/database`.
> Upgraded Firestore to 0.14.0

- src/firestore/firestore.ts
- test/unit/firestore/firestore.spec.ts
`projectId` field is no longer reliably exposed by the Firestore client -- it seems to be lazy initialized.
> Fixing a test failure caused by Firestore 0.14.1 release

- package-lock.json
- package.json
- src/utils/api-request.ts
- test/unit/utils.ts
- test/unit/utils/api-request.spec.ts
The existing HTTP client abstractions (`HttpRequestHandler` and `SignedApiRequestHandler`) have a number of caveats:
1. Do not support HTTP endpoints (HTTPS only)
2. Do not expose response headers
3. Complex and often confusing error handling semantics (e.g. even low-level network errors are reported as errors with HTTP status codes)
4. Support for handling different payload types is broken (e.g. cannot handle anything other than `application/json`, `text/html` and `text/plain`)
5. Not easy to extend or test (public API takes 5 arguments already)
I ran into pretty much all the above problems while prototyping the IAM support for token minting. 
To resolve these problems I propose a new set of HTTP client abstractions (`HttpClient` and `AuthorizedHttpClient`). My original plan was to use …
> Re-implementing the HTTP Client Abstraction

- src/index.d.ts
- src/messaging/messaging.ts
- test/unit/messaging/messaging.spec.ts
- tsconfig.json
Webpush Notification is a struct now: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#webpushconfig
> Update Webpush types in Messaging

- CHANGELOG.md
- src/auth/auth.ts
- src/firestore/firestore.ts
- src/instance-id/instance-id.ts
- src/messaging/messaging.ts
- src/utils/index.ts
- test/unit/auth/auth.spec.ts
- test/unit/firestore/firestore.spec.ts
- test/unit/instance-id/instance-id.spec.ts
- test/unit/utils/index.spec.ts
`GCLOUD_PROJECT` is no longer supported in some managed Google runtimes. `GOOGLE_CLOUD_PROJECT` is the new recommended environment variable.
> Reading projectId from GOOGLE_CLOUD_PROJECT

- CHANGELOG.md
- src/index.d.ts
- src/messaging/messaging.ts
- tsconfig.json
Added DOM types manually. We should keep these in sync with any spec changes.
Also removed ES5 and ES2015.Promise from lib as they are already [included in ES2015](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es2015.d.ts).
Based on offline discussion about #286. Notification types are based on NotificationOptions [from TypeScript](https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.generated.d.ts).
> Remove DOM from lib

- package-lock.json
- package.json
- src/index.d.ts
- test/integration/firestore.spec.ts
* Re-exporting the Firestore Timestamp type
* Updating affected tests
> Upgraded to Firestore 0.15.4

- src/messaging/messaging-api-request.ts
- src/utils/api-request.ts
- test/unit/messaging/messaging.spec.ts
- test/unit/utils.ts
- test/unit/utils/api-request.spec.ts
Using the new `AuthorizedHttpClient` implementation in the FCM code.
This is a follow up of #280 and #291.
Also introducing the `isJson` field to the HTTP response interface, to make it easier to handle JSON-formatted responses.
> Using the new HttpClient in messaging module

- src/auth/credential.ts
- test/unit/auth/auth-api-request.spec.ts
- test/unit/auth/credential.spec.ts
- test/unit/auth/token-generator.spec.ts
- test/unit/firebase.spec.ts
- test/unit/utils.ts
Using the new `HttpClient` API in Credentials module. With this I believe we are using the new API everywhere in the SDK (I will create a separate PR to remove the old code). I also managed to re-enable an old refresh token unit test that had been disabled for a long time.
This is a follow up to #280, #291, and #301
> Using the new HttpClient API in Credentials

- src/instance-id/instance-id-request.ts
- test/unit/instance-id/instance-id-request.spec.ts
Using the new HttpClient API in `instanceId` module.
This is a follow up to #280, #291, #301 and #318
> Using the new HttpClient API in instanceId module

- package.json
A wise man told me we should add the `engines` attribute to our package.json (#328). He's usually right :)
> Adding the engines config to package.json

- CHANGELOG.md
- package-lock.json
- package.json
- src/firestore/firestore.ts
- src/storage/storage.ts
- tslint-test.json
- tslint.json
Since some users frequently encounter installation issues with GCP libraries (when they are not even using them), this PR re-declares those dependencies as `optional`. 
Partially resolves #295
> Made Firestore and GCS Optional Deps

- package-lock.json
- package.json
- src/storage/storage.ts
The breaking changes in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27943  has been released as 1.7.1. This is causing our build to break. This PR fixes it.
> Fixing GCS typings

- src/auth/token-verifier.ts
- test/unit/auth/token-verifier.spec.ts
`verifyIdToken()` API still uses the low-level HTTP API to fetch public keys. This PR updates that code to use the new `HttpClient` interface instead.
> Using HttpClient to fetch public keys

- package.json
- test/integration/auth.spec.ts
- test/integration/firestore.spec.ts
- test/integration/storage.spec.ts
- test/integration/typescript/src/example.test.ts
* Increase mocha timeout to 20s, since some tests occasionally take as long as 10-11s.
* Made all tests honor the timeout configured in package.json (no more test-specific timeouts)
* Cleaning up the app instance after tests in TS smoke test suite to ensure clean termination
> Integration test improvements

- CHANGELOG.md
- src/index.d.ts
- src/messaging/messaging.ts
- test/unit/messaging/messaging.spec.ts
Add subtitle field in ApsAlert payload + tests
> add subtitle in messaging.ApsAlert payload

- package-lock.json
- package.json
A dependency has been pulled from NPM due to a venerability , and it's causing a build break: https://github.com/dominictarr/event-stream/issues/116
Build break: https://travis-ci.org/firebase/firebase-admin-node/jobs/460497899
This PR fixes it by upgrading the affected dependency.
> Updated dependency to fix build error

- CHANGELOG.md
- src/utils/error.ts
- test/unit/utils/error.spec.ts
```
{
"error": {
"errors": [
{
"domain": "global",
"reason": "invalid",
"message": "INVALID_PHONE_NUMBER : Phone number is too short"
}
],
"code": 400,
"message": "INVALID_PHONE_NUMBER : Phone number is too short"
}
}
```
The above will throw error code auth/invalid-phone-number and the
message will be "Phone number is too short".
> Correctly parses error codes with details messages in Firebase Auth.

- src/utils/api-request.ts
- test/unit/utils/api-request.spec.ts
`HttpClient` class currently deep copies the entire request (including headers, data, agent) when making outgoing HTTP calls. If using the`AuthorizedHttpClient`, the request gets deep copied twice. This is done to prevent modifying the request config passed in as the input. However, we only ever modify the headers in `HttpClient`, so we can save a few cycles by only copying them.
> Preventing deep copying the request when making http calls

- src/index.d.ts
- src/messaging/messaging.ts
- src/utils/validator.ts
- test/unit/messaging/messaging.spec.ts
Making `CriticalSound.name` field required. Also disallowing empty strings in the sound config.
> Making CriticalSound.name field required in typings

- test/integration/project-management.spec.ts
Search through the list of apps on a project to find the ones created by
these integration tests, rather than just using the first returned
results.
> Make Project Management list*Apps() integration tests more robust.

- CHANGELOG.md
- package-lock.json
- src/auth/token-verifier.ts
- src/utils/error.ts
- test/unit/auth/token-verifier.spec.ts
> Implemented errors codes for expired ID tokens and session cookies

- test/unit/auth/auth-api-request.spec.ts
- test/unit/auth/auth.spec.ts
- test/unit/auth/credential.spec.ts
- test/unit/auth/token-generator.spec.ts
- test/unit/firebase-app.spec.ts
- test/unit/firebase-namespace.spec.ts
- test/unit/firebase.spec.ts
- test/unit/instance-id/instance-id-request.spec.ts
- test/unit/instance-id/instance-id.spec.ts
- test/unit/messaging/messaging.spec.ts
- test/unit/project-management/project-management-api-request.spec.ts
- test/unit/utils.ts
- test/unit/utils/api-request.spec.ts
I want to implement some changes to our credentials, but every time I touch that code a large number of unit tests break. This is because many of our unit tests are tightly coupled with the credentials. A lot of the tests emulate the behavior of credentials by mocking the HTTP call to token servers, and if the credentials change how they talk to the servers even slightly, all the dependent tests break.
This PR reduces this level of coupling by implementing the following changes:
1. Service-level unit tests (auth, fcm etc.) no longer mock the HTTP call to token servers. Instead, they stub the `FirebaseApp.Internals.getToken()` method.
2. `FirebaseApp` and `FirebaseNamespace` unit tests stub the `getAccessToken()` method on the credential classes.
3. Only the `Credential` unit tests are …
> Refactoring unit tests to reduce dependency on credentials

- CHANGELOG.md
- src/auth/credential.ts
- test/unit/auth/credential.spec.ts
- test/unit/firebase-app.spec.ts
The error handling in Firebase credentials has been broken due to a bug introduced while migrating to the `HttpClient` API. Specifically, when credentials fail to fetch an access token, they no longer include the original server error in the exceptions thrown. This prevents more higher level classes like `FirebaseApp` from reporting verbose errors.
This PR fixes the issue, and adds test cases to verify the behavior.
> Fixing error handling in Firebase credentials

- CHANGELOG.md
- package-lock.json
- package.json
- test/integration/typescript/tsconfig.json
Also updated one of the test configuration files to prevent the following error:
```
+ firebase-admin@7.0.0
added 278 packages in 12.228s
> tsc -p tsconfig.json
node_modules/google-auth-library/build/src/auth/oauth2client.d.ts:280:37 - error TS2583: Cannot find name 'Map'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.
280     protected refreshTokenPromises: Map<string, Promise<GetTokenResponse>>;
~~~
Found 1 error.
```
> Bumped version to 7.0.0

- createReleaseTarball.sh
- package.json
Without the "prepare" rule, the TypeScript compile is not invoked when installing this package directly from GitHub.
> Ability to install package from GitHub

- CHANGELOG.md
- src/index.d.ts
- src/messaging/messaging-types.ts
- src/messaging/messaging.ts
- test/integration/messaging.spec.ts
- test/unit/messaging/messaging.spec.ts
This is a follow up to #453. The `sendMulticast()` API uses the `sendAll()` method to send a single message to a batch of 100 tokens.
> Implementing the sendMulticast() API for FCM

- CHANGELOG.md
- src/messaging/messaging.ts
- test/unit/messaging/messaging.spec.ts
> Using the correct message copies in sendAll() API

- CHANGELOG.md
- package-lock.json
- package.json
- src/firebase-namespace.ts
- src/index.d.ts
- test/unit/firebase-namespace.spec.ts
This upgrades the Firestore dependency to v1.2 and exposes the `v1` and `v1beta` namespaces.
> Expose Firestore v1 and v1beta1 namespaces

- test/unit/firebase-app.spec.ts
It seems a new version of TypeScript is unable to compile some of our test sources. See https://travis-ci.org/firebase/firebase-admin-node/jobs/514363968
```
/home/travis/build/firebase/firebase-admin-node/node_modules/ts-node/src/index.ts:307
throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
^
TSError: ⨯ Unable to compile TypeScript
test/unit/firebase-app.spec.ts (78,10): Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature. (7017)
test/unit/firebase-app.spec.ts (93,10): Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature. (7017)
test/unit/firebase-app.spec.ts (678,14): Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature. (7017)
```
> Fixing a TS compilation error in tests

- src/messaging/batch-request.ts
- src/messaging/messaging-api-request.ts
- test/unit/messaging/batch-requests.spec.ts
- test/unit/messaging/messaging.spec.ts
* Adding `commonHeaders` to all sub requests in a batch. This includes the `X-Firebase-Client` header.
* Removing `access_token_auth` header from batch requests (this is only needed for the legacy API calls).
> Adding common headers to all sub requests in FCM batch API

- src/index.d.ts
ThenableReference implements a `.catch()` method, but `ref.push(...).catch(...)` generates a TypeScript error, since neither the `Reference` nor `PromiseLike` interfaces have that method.
This change was [already done on the JS SDK](https://github.com/firebase/firebase-js-sdk/pull/1462) back in January, and this PR simply puts the admin SDK back in line with it.
PS: This fixes issue #144, which was already closed.
> ThenableReference should extend Promise, not PromiseLike

- README.md
Recommending developers to use Node 8+.
> Documentation update (Node 6 deprecation)

- docgen/content-sources/node/toc.yaml
- docgen/generate-docs.js
- package-lock.json
- package.json
This implementation extracts the list of re-exported Firestore types from `index.d.ts`, and adds them to the auto-generated Firestore documentation.
Screenshot of output:
> Auto-generating links to re-exported Firestore types

- README.md
- src/utils/api-request.ts
- src/utils/error.ts
- test/unit/utils/api-request.spec.ts
The existing `HttpClient` retries all HTTP requests once that are failing due to connection timeout and reset errors. We would like to further extend this retries support to meet the following new requirements:
1. Ability to retry requests on specific HTTP error codes (e.g. 503)
2. Ability to delay subsequent retries according to the `Retry-After` header sent by the server
3. Ability to use exponential backoff
4. Ability to configure retries for individual services in the SDK
In order to meet all the above requirements, this PR introduces a new internal interface called `RetryConfig`. The `HttpClient` optionally takes a `RetryConfig` as a constructor parameter, and retries failing requests based on that. 
For the moment, we use the following as the default `RetryConfig` in order to retain …
> Internal API for retrying HTTP requests

- src/auth/auth-config.ts
- src/auth/tenant.ts
- src/auth/user-import-builder.ts
- src/auth/user-record.ts
- src/index.d.ts
- src/utils/error.ts
- test/unit/auth/auth-config.spec.ts
- test/unit/auth/tenant.spec.ts
- test/unit/auth/user-import-builder.spec.ts
- test/unit/auth/user-record.spec.ts
- test/unit/index.spec.ts
- Defining type definitions.
- Adding tenantId to UserRecord and UserImportBuilder.
- Adding new errors associated with tenant operations.
- Defines the Tenant object.
As the changes are quite large. This will be split into multiple PRs.
> Starts defining multi-tenancy APIs. This includes:

- src/index.d.ts
Porting over comment for RTDB and admin.credential for TypeDoc reference generation.
Staged internally at https://firebase.devsite.corp.google.com/docs/reference/admin/node/admin.credential, https://firebase.devsite.corp.google.com/docs/reference/admin/node/admin.database.
Thanks!
> Credential db

- src/auth/auth-api-request.ts
- src/auth/auth.ts
- src/utils/error.ts
- test/unit/auth/auth-api-request.spec.ts
- test/unit/auth/auth.spec.ts
Defines BaseFirebaseAuthRequestHandler class for sending Auth requests related to user management APIs and SAML/OIDC config mgmt APIs, link generation, etc.
Defines FirebaseAuthRequestHandler which extends the base class for project level only calls and which will also be extended to include tenant mgmt APIs.
Defines FirebaseTenantRequestHandler which extends the base class for tenant level only calls.
Unit tests have been modified to run tests on both subclasses. 99% of the unit test logic is the same. It has been tweaked to accept a common interface handler. 2 tests are run for each. One for FirebaseAuthRequestHandler and another for FirebaseTenantRequestHandler.
> Multi-tenancy changes to shared Auth API requests

- src/index.d.ts
These would be the last comments to add before generating the reference.
Staged internally at https://firebase.devsite.corp.google.com/docs/reference/admin/node/admin.projectManagement
Thanks!
> Adding comments for admin.projectManagement.

- .travis.yml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
- src/index.d.ts
- src/utils/api-request.ts
- src/utils/error.ts
- test/unit/utils/api-request.spec.ts
> Merging changes with master.

- src/auth/auth-api-request.ts
- src/auth/auth.ts
- src/utils/error.ts
- test/unit/auth/auth-api-request.spec.ts
- test/unit/auth/auth.spec.ts
Defines TenantAwareAuth and its user management APIs, email action link APIs, OIDC/SAML provider config mgmt APIs.
> Defines TenantAwareAuth

- CHANGELOG.md
- src/utils/api-request.ts
- test/unit/messaging/messaging.spec.ts
- test/unit/utils/api-request.spec.ts
* Increased retry count to 4
* Backoff factor set to 0.5 (this results in the delay pattern of 0s, 1s, 2s and 4s)
> Automatically retrying on 503 errors

- src/auth/auth-api-request.ts
- test/unit/auth/auth-api-request.spec.ts
Defines tenant management API on AuthRequestHandler.
> Defines tenant management API on AuthRequestHandler.

- src/auth/auth.ts
- src/utils/error.ts
- test/unit/auth/auth.spec.ts
This includes getTenant, deleteTenant, listTenants, createTenant and updateTenant.
This expects TenantServerResponse to be returned for createTenant and updateTenant.
Expected results have not been confirmed. A followup PR will add integration tests for the above.
> Adds tenant management APIs to developer facing Auth instance.

- src/auth/credential.ts
- test/unit/auth/credential.spec.ts
Updating the the v1 URL of the metadata service, and adding the required header.
https://cloud.google.com/compute/docs/storing-retrieving-metadata#transitioning
Resolves #560
> Updating the metadata server URL for Application Default Credentials

- CHANGELOG.md
- src/messaging/messaging.ts
- test/unit/messaging/messaging.spec.ts
In  newer JS specs like `es2015`, custom array types can have a constructor that is not `Array`.
```
class CustomArray extends Array { }
const arr = new CustomArray();
console.log(Array.isArray(arr), arr.constructor);
```
ES5 output: true [Function: Array]
ES2015 output: true [Function: CustomArray]
Our `utils.deepCopy()` method does not correctly copy such objects, which sometimes causes unusual behaviors. This fixes the issue for the FCM APIs affected by this problem.
Ideally, we should push this fix down into the `deepCopy()` method. But that would affect all the modules. I'd prefer to test this out with FCM first, and if all looks good move the fix to `deepCopy()` in the future.
Resolves #566
> Gracefully handling array-like arguments in sendAll()/sendMulticast()

- docgen/content-sources/node/toc.yaml
- docgen/generate-docs.js
We have several `enum` types in our public API, and TypeDoc generates their documentation in a `/enums` subdirectory. This modifies the docgen script to move the enum docs to the root.
>  Special handling logic for enum docs

- src/index.d.ts
Defines Auth multi-tenancy references in index.d.ts.
> Defines Auth multi-tenancy references in index.d.ts.

- src/auth/credential.ts
- src/auth/token-generator.ts
- src/firestore/firestore.ts
- src/storage/storage.ts
- src/utils/index.ts
- test/unit/auth/credential.spec.ts
`Credential` is a public interface and is declared as follows in the typings:
```
interface Credential {
getAccessToken(): Promise<admin.GoogleOAuthAccessToken>;
}
```
But in the actual implementation (credential.ts), there's an additional method in the interface:
https://github.com/firebase/firebase-admin-node/blob/843df1229405d441fd5e8bd4170e38cd9fd4cbd4/src/auth/credential.ts#L291-L294
This can cause issues if the developer implements the public `Credential` interface, and passes it through `AppOptions`. Internal code that expects to find a `getCertificate()` method will fail.
This PR addresses this issue by separating the `getCertificate()` method from the `Credential` interface.
Resolves #573
> Removing getCertificate() from the Credential interface

- test/integration/auth.spec.ts
- User management
- Custom claims
- Import users
- List users
- Token revocation
- Email link generation (skipped due to backend bug)
- OIDC/SAML management APIs.
> Adds basic integration tests for the following in multi-tenancy context:

- package-lock.json
- package.json
We have a few users depending on the latest version of `google-auth-library`, which is dependent on using the latest version of `@google-cloud/storage`.  The only breaking change should be the supported versions of node (8 and up), which is already the case for this lib as far as I can tell.
> fix(deps): upgrade to v3 of @google-cloud/storage

- package.json
- src/database/database.ts
- test/unit/firebase-app.spec.ts
- test/unit/firebase.spec.ts
Support specifying database endpoint with FIREBASE_DATABASE_EMULATOR_HOST.
> add FIREBASE_DATABASE_EMULATOR_HOST_VAR

- CHANGELOG.md
- src/database/database.ts
- src/index.d.ts
- test/integration/database.spec.ts
- test/unit/database/database.spec.ts
- test/unit/utils/api-request.spec.ts
New APIs for getting and setting RTDB rules:
```
getRules(): Promise<string>
getRulesJSON(): Promise<object>
setRules(source: string|Buffer|object): Promise<void>
```
New methods are dynamically injected to the `Database` object returned by the `@firebase/database` package. Type-safety is maintained by defining a new interface with the same name, letting TS declaration merging to take effect.
go/firebase-rules-admin
Related to #504
> API for managing RTDB Security Rules

- src/database/database.ts
- test/unit/firebase-app.spec.ts
- test/unit/firebase.spec.ts
This reverts commit e963005658a0e5e24c0af7eb247a5461bc89a6a6. With the new way we're handling this variable in the firebase-js-sdk (https://github.com/firebase/firebase-js-sdk/pull/2016), we won't need to handle it in this repo anymore.
> Revert "add FIREBASE_DATABASE_EMULATOR_HOST_VAR (#596)"

- src/security-rules/security-rules-api-client.ts
- src/security-rules/security-rules-utils.ts
- src/security-rules/security-rules.ts
- src/utils/error.ts
- test/unit/index.spec.ts
- test/unit/security-rules/security-rules-api-client.spec.ts
- test/unit/security-rules/security-rules.spec.ts
Added the base framework for the new security rules API (nothing new exposed in the public API --i.e. `admin` namespace -- yet). This PR specifically adds the `SecurityRules` class and the following 2 methods:
* `getRuleset()`
* `getFirestoreRuleset()`
Also defined the types `Ruleset`, `RulesetMetadata` and `RulesFile`  which will be added to the public API in the future.
go/firebase-rules-admin
> Implementing the Firebase Security Rules API

- src/security-rules/security-rules-api-client.ts
- src/security-rules/security-rules.ts
- test/unit/security-rules/security-rules-api-client.spec.ts
- test/unit/security-rules/security-rules.spec.ts
Added the `SecurityRules.deleteRuleset()` method.
go/firebase-rules-admin
> Implemented the deleteRuleset() API

- src/security-rules/security-rules-api-client.ts
- src/security-rules/security-rules.ts
- test/unit/security-rules/security-rules-api-client.spec.ts
- test/unit/security-rules/security-rules.spec.ts
Implemented the `releaseFirestoreRuleset()` API. This attempts to PATCH the existing release.
> Implemented the API for releasing rulesets

- src/auth/tenant.ts
- src/index.d.ts
- test/integration/auth.spec.ts
- test/unit/auth/auth-api-request.spec.ts
- test/unit/auth/auth.spec.ts
- test/unit/auth/tenant.spec.ts
All tenants are now created in lightweight state by default.
Note the underlying backend change is not yet in production.
> Removes all usage of tenant types.

- src/security-rules/security-rules.ts
- test/unit/security-rules/security-rules.spec.ts
Implementing the rest of the release ruleset APIs.
```
releaseStorageRuleset(ruleset: string | RulesetMetadata, bucket?: string): Promise<void>
releaseFirestoreRulesetFromSource(source: string | Buffer): Promise<Ruleset>
releaseStorageRulesetFromSource(source: string | RulesetMetadata, bucket?: string): Promise<Ruleset>
```
> Implementing the remaining releaseRuleset APIs

- src/security-rules/security-rules-api-client.ts
- src/security-rules/security-rules.ts
- test/unit/security-rules/security-rules-api-client.spec.ts
- test/unit/security-rules/security-rules.spec.ts
1. Added the `listRulesetMetadata()` method with support for paging through rulesets.
2. Added the `RulesetMetadataList` interface to represent the return value.
This completes the implementation of the `security-rules` module. Once this is done, we will need a couple more PRs to get this hooked up to the `admin` namespace and implement the integration tests.
> Implemented the listRulesetMetadata() API

- test/integration/auth.spec.ts
- Enables email action link generation tests after backend bug was fixed.
- Adds email link sign-in test case.
- Fixes issues with nested multi-tenancy tests not being skipped when they are supposed to.
Confirmed multi-tenancy integration tests are passing in production.
> Updates multi-tenancy integration tests.

- docgen/content-sources/node/toc.yaml
- src/firebase-app.ts
- src/firebase-namespace.ts
- src/index.d.ts
- test/unit/firebase-app.spec.ts
- test/unit/firebase-namespace.spec.ts
1. Exposed the `admin.securityRules` namespace and the getter.
2. Exposed `securityRules` getter from `FirebaseApp`.
3. Updated the `index.d.ts` file.
The comments in the `d.ts` file gets compiled into our API reference docs.
> Adding the rules API to the public API surface

- src/index.d.ts
- src/messaging/messaging-types.ts
- test/integration/messaging.spec.ts
- test/unit/messaging/messaging.spec.ts
* Add image in notification support
* Add unit tests and modified integration test to reflect this change
* In Firebase Cloud Messaging, added 'image' field in the general Notification class, the AndroidNotification class, and the ApnsFcmOptions class.
RELEASE NOTE: Added new APIs for specifying an image URL in notifications.
Resolves #598
> feat(fcm): Add image in notification support

- CONTRIBUTING.md
- src/auth/user-record.ts
- test/integration/auth.spec.ts
- test/unit/auth/auth.spec.ts
- test/unit/auth/user-record.spec.ts
These values *look* like passwords hashes, but aren't, leading to
potential confusion.
Additionally, added docs to CONTRIBUTING.md detailing how to add the
permission that causes password hashes to be properly returned as well
as adjusting the test failure message should the developer not add that
permission.
b/141189502
> Remove (base64) 'REDACTED' passwords from user records.

- docgen/generate-docs.js
- package-lock.json
- package.json
Resolves a few npm audit warnings in the old version.
> Upgraded Typedoc to latest

- package-lock.json
- src/index.d.ts
- test/integration/auth.spec.ts
Updates d.ts definition for `setCustomUserClaims` to allow nulls for custom user claims.
Passing null will clear existing claims.
Added integration tests for clearing custom claims.
Resolves #667
> Updates d.ts definition for `setCustomUserClaims` to allow nulls for custom user claims

- src/index.d.ts
Replaced `’` with `'` as the former was not supported in some editors (most notably emacs).
Plus a few spacing/formatting updates automatically applied by the TS code formatter.
> Replacing non-standard punctuation with standard single quote

- src/project-management/android-app.ts
- src/utils/error.ts
- test/integration/project-management.spec.ts
- test/unit/project-management/android-app.spec.ts
Without this, the sdk will send a null resourceName to the server,
resulting in a somewhat misleading 404 error being returned.
> Check for null resourceName before attempted to delete a cert

- test/integration/security-rules.spec.ts
Previously, this would work:
yarn test:integration --updateRules --grep 'admin.securityRules'
but this would not:
yarn test:integration --updateRules --grep 'admin.securityRules.getRuleset\(\).rejects with not-found'
because that test relied on side effects from earier tests, making this
test suite difficult to debug.
> Break test order dependencies in security-rules integration tests.

- tsconfig.json
Specifically, noImplicitThis, alwaysStrict, strictBindCallApply. No
changes to the source were required; we were already compliant with
these options.
> Enable stricter tsconfig compilerOptions

- src/auth/user-record.ts
- test/unit/auth/user-record.spec.ts
Updates UserRecord to parse multi-factor related information from the GetAccountInfo server response.
First step in supporting multi-factor authentication with SMS as a second factor.
> Populates UserRecord with multi-factor related info

- src/index.d.ts
- src/messaging/messaging.ts
- test/integration/messaging.spec.ts
- test/unit/messaging/messaging.spec.ts
RELEASE NOTE: Batch messaging APIs `sendAll()` and `sendMulticast()` now support sending up to 500 messages in a single call.
> fix(fcm): Increased FCM batch request limit to 500

- package-lock.json
- package.json
Update Firebase dependencies, all tests passed locally
RELEASE NOTE: feat(firestore): Upgraded `@google-cloud/firestore` dependency version to 2.6.0.
RELEASE NOTE: change(storage): Upgraded `@google-cloud/storage` dependency version to 4.1.2. This version contains some minor breaking changes. Check [release notes](https://github.com/googleapis/nodejs-storage/releases/tag/v4.0.0) of the dependency for more information.
> chore(deps): bump firebase deps

- src/auth/auth-api-request.ts
- src/auth/user-import-builder.ts
- src/utils/error.ts
- src/utils/validator.ts
- test/integration/auth.spec.ts
- test/unit/auth/auth-api-request.spec.ts
- test/unit/auth/auth.spec.ts
- test/unit/auth/user-import-builder.spec.ts
- test/unit/utils/validator.spec.ts
WIP: Adds ability to import users with phone second factors.
> Adds ability to import users with phone second factors.

- src/auth/auth-api-request.ts
- src/auth/user-import-builder.ts
- src/auth/user-record.ts
- src/index.d.ts
- test/integration/auth.spec.ts
- test/unit/auth/auth-api-request.spec.ts
Adds multi-factor support for updateUser
This will allow the ability to update the list of second factors on an existing user record.
Adds related unit and integration tests for this operation.
> Adds multi-factor support for updateUser

- src/messaging/messaging.ts
- test/unit/messaging/messaging.spec.ts
Resolves #712 
RELEASE NOTE: `sendMulticast()` API now correctly copies the `fcmOptions` when sending a message to multiple recipients.
> fix(fcm): Copying fcmOptions when multicasting messages

- package-lock.json
- package.json
- src/utils/api-request.ts
New TS compiler flagged a semantic error in `api-request.ts` which I have fixed here.
> Upgraded Typescript to 3.7.x

- src/auth/auth-api-request.ts
- src/auth/user-import-builder.ts
- src/auth/user-record.ts
- src/index.d.ts
- test/integration/auth.spec.ts
- test/unit/auth/auth-api-request.spec.ts
Extends createUser to support multi-factor user creation.
Note that only phoneNumber and displayName are allowed to be passed in this operation.
Adds relevant unit and integration tests.
This capability is only available in staging.
> Extends createUser to support multi-factor user creation.

- src/auth/auth.ts
- src/auth/token-verifier.ts
- src/utils/index.ts
- test/unit/auth/auth.spec.ts
- test/unit/auth/token-verifier.spec.ts
- test/unit/utils/index.spec.ts
Currently the SDK uses the following synchronous procedure to determine the project ID:
1. Get project ID from AppOptions.
2. Get project ID from the service account credentials.
3. Get project ID from the environment variables.
New GCP runtimes like Cloud Run no longer expose the project ID as environment variables. Therefore the SDK does not work in these environments if the project ID is not specified via AppOptions or service account credentials (see b/143090254). 
```
admin.initializeApp();
admin.auth().verifyIdToken(token); // does not work in Cloud Run
```
To support this we need to get the project ID from the local metadata server. This is an async operation, and therefore we need to turn our project ID discovery logic into an async method.
With this PR I'm starting to refactor …
> Async API to determine project ID

- src/index.d.ts
Fix an inconsistency where `hash.saltSeparator` on `UserImportOptions` is expecting a `Buffer` but its type on Typescript module was specified as a `string`
> Changes saltSeparator type from string to Buffer

- src/instance-id/instance-id-request.ts
- test/unit/instance-id/instance-id-request.spec.ts
RELEASE NOTE: Fixed a bug in the `admin.instanceId().deleteInstanceId()` API that caused errors even when the operation completed successfully in the backend.
b/139957032
> fix: Fixing a response parse error in IID delete API

- src/auth/auth-api-request.ts
- src/messaging/messaging.ts
- test/unit/auth/auth.spec.ts
- test/unit/messaging/messaging.spec.ts
Continuation of #715 
Using `utils.findProjectId()` in Auth and FCM.
> Using async project ID discovery API in Auth and FCM

- test/unit/auth/auth.spec.ts
Following 2 test failures have been observed in the master branch in some environments (mainly Google Cloud Build).
```
Step #3:   2 failing
Step #3: 
Step #3:   1) Auth
Step #3:        createCustomToken()
Step #3:          should be eventually rejected if a cert credential is not specified:
Step #3:      AssertionError: expected [Error: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.; Please refer to https://firebase.google.com/docs/auth/admin/create-custom-tokens for more details on how to use and troubleshoot this feature. Raw server response: "{"error":{"code":401,"message":"Request had invalid authentication credentials. …
```
> Fixing a flaky auth test case

- package-lock.json
- package.json
RELEASE NOTE: Upgraded the `@google-cloud/firestore` dependency to v3.0.0. Please check Firestore [release notes](https://github.com/googleapis/nodejs-firestore/tree/v3.0.0) for more details.
> feat: Update Firestore to 3.0

- src/security-rules/security-rules-api-client.ts
- src/security-rules/security-rules.ts
- test/unit/security-rules/security-rules-api-client.spec.ts
- test/unit/security-rules/security-rules.spec.ts
Continuation of #715
Using `utils.findProjectId()` in `SecurityRules`.
> Using async project ID discovery API in SecurityRules

- CONTRIBUTING.md
- createReleaseTarball.sh
Also document how to enable these tests in the CONTRIBUTING.md file.
> Enable tenant management tests for releases.

- src/auth/credential.ts
- src/auth/token-generator.ts
- src/firebase-app.ts
- src/firebase-namespace.ts
- src/firestore/firestore.ts
- src/storage/storage.ts
- src/utils/index.ts
- test/resources/mocks.ts
- test/unit/auth/auth.spec.ts
- test/unit/auth/credential.spec.ts
- test/unit/auth/token-generator.spec.ts
- test/unit/auth/token-verifier.spec.ts
- test/unit/firebase-app.spec.ts
- test/unit/firebase.spec.ts
- test/unit/firestore/firestore.spec.ts
Refactoring and simplifying the existing credential implementation for better design and async project ID discovery.
* `CertCredential` class was renamed to `ServiceAccountCredential`.
* `Certificate` type is renamed to `ServiceAccount`, and is no longer exported. Instead the `projectId`, `clientEmail` and `privateKey` properties are directly exposed from the `ServiceAccountCredential` class.
* `MetadataServiceCredential` class was renamed to `ComputeEngineCredential`. This class now also has `getProjectId(): Promise<string>` method to discover the project ID from the Compute Engine environment.
* `ApplicationDefaultCredential` class has been removed. Instead now there's a `getApplicationDefault()` function that returns a `Credential` implementation suitable for the environment.
> Refactored the credentials implementation

- src/auth/user-import-builder.ts
- src/utils/error.ts
- test/integration/auth.spec.ts
- test/unit/auth/auth-api-request.spec.ts
- test/unit/auth/user-import-builder.spec.ts
Adds backend multi-factor auth related errors and their client mappings.
> Adds backend multi-factor auth related errors and their client mappings.

- src/auth/credential.ts
- src/firestore/firestore.ts
- src/storage/storage.ts
- src/utils/index.ts
- test/unit/auth/credential.spec.ts
- test/unit/utils/index.spec.ts
Support for auto discovering the project ID when running on Compute Engine, Cloud Run etc.
Verified by running a build on a Compute Engine instance.
> Discovering project ID from the local metadata service

- src/auth/credential.ts
- src/firestore/firestore.ts
- src/storage/storage.ts
- test/unit/auth/credential.spec.ts
- test/unit/firebase.spec.ts
- test/unit/firestore/firestore.spec.ts
Modules like Firestore and Storage used to have the following bit of code:
https://github.com/firebase/firebase-admin-node/blob/00892e0b1f4c2e588834f81522f77387eab2e3c9/src/firestore/firestore.ts#L98-L110
This allowed checking if the SDK was initialized with ADC, and if so delegating the credential loading back to the corresponding GCP library. In other cases (e.g. custom credentials), an error was thrown.
But in the v8.9.1 release this code was refactored into this:
https://github.com/firebase/firebase-admin-node/blob/5ce91759724528dd574c14a4b3637230d691d4a8/src/firestore/firestore.ts#L88-L100
But this is not quite equivalent to the logic we used to have, because:
```
ApplicationDefaultCredential = 
MetadataServiceCredential |
RefreshTokenCredential loaded from well-known path | …
```
> fix: Differentiating explicitly loaded vs default credentials

- src/auth/auth.ts
- src/index.d.ts
Adds missing multi-factor related claims to the `DecodedIdToken` interface.
> Defines the d.ts multi-factor related comments for reference generation.

- src/firebase-app.ts
- src/firebase-namespace.ts
- src/index.d.ts
- src/machine-learning/machine-learning.ts
- test/unit/firebase-app.spec.ts
- test/unit/firebase-namespace.spec.ts
Firebase ML Node.js SDK Structure. (Implementation to follow)
> Firebase ML Node.js SDK Structure

- src/index.d.ts
- src/machine-learning/machine-learning-api-client.ts
- src/machine-learning/machine-learning-utils.ts
- src/machine-learning/machine-learning.ts
- test/integration/machine-learning.spec.ts
- test/unit/index.spec.ts
- test/unit/machine-learning/machine-learning-api-client.spec.ts
- test/unit/machine-learning/machine-learning.spec.ts
Added Firebase Machine Learning GetModel functionality and tests
> Added GetModel functionality and tests

- src/machine-learning/machine-learning-api-client.ts
- src/machine-learning/machine-learning.ts
- test/integration/machine-learning.spec.ts
- test/unit/machine-learning/machine-learning-api-client.spec.ts
- test/unit/machine-learning/machine-learning.spec.ts
Added DeleteModel functionality and tests
> Added DeleteModel functionality and tests

- src/machine-learning/machine-learning-api-client.ts
- src/machine-learning/machine-learning.ts
- test/integration/machine-learning.spec.ts
- test/unit/machine-learning/machine-learning-api-client.spec.ts
- test/unit/machine-learning/machine-learning.spec.ts
Added UpdateModel, publishModel,and unpublishModel functionality + tests
> Added UpdateModel, publishModel,and unpublishModel functionality + tests

- src/index.d.ts
- src/machine-learning/machine-learning-api-client.ts
- src/machine-learning/machine-learning.ts
- test/integration/machine-learning.spec.ts
- test/unit/machine-learning/machine-learning-api-client.spec.ts
- test/unit/machine-learning/machine-learning.spec.ts
- test/unit/utils/api-request.spec.ts
Added ListModels functionality for Firebase ML
> Added ListModels functionality for Firebase ML

- test/integration/database.spec.ts
Introduced by https://github.com/firebase/firebase-admin-node/pull/790
> Fix compilation error in integration tests

- .github/workflows/ci.yml
- .github/workflows/release.yml
- package.json
- test/integration/auth.spec.ts
Note that this won't actually run them.
Additionally, the *unit* tests are also built, impying that we're
building them twice (once during this step, and possibly again when
running the unit tests.)
> Build integration tests during CI (and release)

- src/auth/auth-api-request.ts
- test/unit/auth/auth-api-request.spec.ts
This also makes it consistent with the comments a few lines above, as
well as the integration test.
> Fix revokeRefreshTokens to round consistently with the other platforms.

- src/remote-config/remote-config-api-client.ts
- src/remote-config/remote-config-utils.ts
- src/remote-config/remote-config.ts
- test/unit/index.spec.ts
- test/unit/remote-config/remote-config-api-client.spec.ts
- test/unit/remote-config/remote-config.spec.ts
- Implement `getTemplate()`
- Introduce new `RemoteConfigParameterValue` type
- To closely represent the backend REST API, change `parameters` in `RemoteConfigTemplate` to a hashmap
- Add unit tests for `getTemplate`
> Add getTemplate functionality

- src/index.d.ts
This is causing errors in the reference generation process.
> Removes special char from index.d.ts.

- .github/scripts/publish_package.sh
- .npmrc
Creating the .npmrc file at the root of the repo as instructed in https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow#set-the-token-as-an-environment-variable-on-the-cicd-server
> chore: Adding a .npmrc file to the root of the repo

- src/remote-config/remote-config-api-client.ts
- src/remote-config/remote-config-utils.ts
- src/remote-config/remote-config.ts
- test/unit/remote-config/remote-config-api-client.spec.ts
- test/unit/remote-config/remote-config.spec.ts
- Add `validateTemplate(...)` operation
- Add unit tests for `validateTemplate`
> Add validate template functionality

- .github/scripts/publish_package.sh
Using relative path in `npm publish` command.
> [chore] Release 8.10.0 (take 2)

- src/machine-learning/machine-learning-api-client.ts
- test/unit/machine-learning/machine-learning-api-client.spec.ts
Changed the endpoint to firebaseml.googleapis.com/v1beta2
> Firebase ML changed endpoint

- src/remote-config/remote-config-api-client.ts
- src/remote-config/remote-config.ts
- test/unit/remote-config/remote-config-api-client.spec.ts
- test/unit/remote-config/remote-config.spec.ts
- Implement publishTemplate()
- Add force publish support
- Add unit tests for publish template
> Add publish template operation

- src/index.d.ts
Per internal bug report 149696213.
Staged internally at https://firebase.devsite.corp.google.com/docs/reference/admin/node/admin.messaging.NotificationMessagePayload#sound
Thanks!
> Fixing Android notification options descriptions

- src/remote-config/remote-config.ts
- test/unit/remote-config/remote-config.spec.ts
- Add `createTemplateFromJSON(...)`
> Add method to create a template from JSON string

- src/firebase-app.ts
- src/firebase-namespace.ts
- src/index.d.ts
- test/unit/firebase-app.spec.ts
- test/unit/firebase-namespace.spec.ts
- test/unit/firebase.spec.ts
- Add interfaces to` index.d.ts`
Note: Integration tests will be added in an upcoming PR
> Add interfaces to index.d.ts

- src/remote-config/remote-config-api-client.ts
- test/integration/remote-config.spec.ts
- test/unit/remote-config/remote-config.spec.ts
- Add integrations test for the RC API
- Add a function to validate templates passed into `validateTemplate()` and `publishTemplate()` functions
- Add unit tests for the new validations
> Add integration tests for Remote Config

- src/index.d.ts
- src/remote-config/remote-config-api-client.ts
- test/unit/remote-config/remote-config-api-client.spec.ts
- test/unit/remote-config/remote-config.spec.ts
- Add an enum to list all the valid tag colors for conditions
Note: API is still under review. Getting a head start here. Should merge after #826
> Add condition tag colors list

- docgen/content-sources/node/toc.yaml
- src/auth.d.ts
- test/integration/auth.spec.ts
Typings of the `UserImportRecord` interface had been broken by https://github.com/firebase/firebase-admin-node/commit/564cbe5ffa8766d74c06bada951071efe1b361e9
Further more the `multifactor` configuration was never added to this type. The integration tests use `any` for this type and hence the errors were never surfaced.
This PR addresses all the above.
> fix(auth): Fixing UserImportRecord typings declaration

- src/index.d.ts
- test/integration/remote-config.spec.ts
- Convert TagColor enum to a union type to fix integration tests
> Convert TagColor enum to a union type to fix integration tests

- src/index.d.ts
- src/remote-config/remote-config-api-client.ts
- src/remote-config/remote-config.ts
- test/integration/remote-config.spec.ts
- test/unit/remote-config/remote-config-api-client.spec.ts
- test/unit/remote-config/remote-config.spec.ts
- Add support for RC Parameter Groups
- Add integration tests
> Add support for Remote Config parameter groups

- docgen/content-sources/node/toc.yaml
- src/index.d.ts
- Add a more descriptive comment explaining what `force` updates are in `publishTempalte()` `options`.
- Add the new types to `toc.yaml`
> Update docs for RC publish template options

- src/remote-config/remote-config.ts
- test/integration/remote-config.spec.ts
- test/unit/remote-config/remote-config.spec.ts
- Add `toJSON()` method to `RemoteConfigTemplateImpl` to correctly serialize the JSON object
> Add toJSON method to Remote Config Template implementation

- src/database.d.ts
This syncs the types with https://github.com/firebase/firebase-js-sdk/blob/master/packages/database-types/index.d.ts
Fixes https://github.com/firebase/firebase-admin-node/issues/805
> Update Database types

- src/auth.d.ts
- src/auth/auth.ts
Fixes https://github.com/firebase/firebase-admin-node/issues/846
RELEASE NOTE: Exposed `email`, `email_verified`, `phone_number` and `picture` fields from the `DecodedIdToken` type.
> fix(auth): Defines missing `DecodedIdToken` types.

- docgen/content-sources/node/toc.yaml
- Remove type aliases from toc.yaml
Type doc complaints about missing files when generating docs. This PR removes the type aliases in `toc.yaml` causing the missing file paths.
> Remove type aliases from toc.yaml

- src/index.d.ts
- src/remote-config/remote-config-api-client.ts
- src/remote-config/remote-config.ts
- test/unit/remote-config/remote-config-api-client.spec.ts
- Add support to get remote config template by version number
NOTE: API proposal is still under review. Getting a head start
> Get remote config template by version number

- src/auth.d.ts
While it's always present (even if null), having it optional allows
existing code that implements this interface to not break.
Fixes: #880
> fix(auth): Mark UserMetadata::lastRefreshTime as optional.

- test/unit/remote-config/remote-config-api-client.spec.ts
- test/unit/remote-config/remote-config.spec.ts
Our unit tests for RC are quite repetitive. As we are adding more features to the RC API, it is time to clean up the code a bit.
- Add reusable functions for repetitive tests.
- Move input validation tests from `remote-config.spec.ts` to `remote-config-api-client.spec.ts` as that is where the validation really takes place.
> Refactor unit tests for Remote Config

- .github/workflows/ci.yml
Unless we trigger this workflow on `pull_request` event, we won't get CI coverage for pull requests sent by external contributors.
> chore: Running CI workflow on pull_request

- src/messaging.d.ts
The comments regarding the `NotificationMessagePayload` were not correct. They were placed with different options.  
The comment related to `tag` was attached to `sound` and `tag` did not have any comment attached.  
Had an issue understanding the payload the first time I opened the installed directory to go through the payload of `sendToDevice`
> Rectified issues in comments for NotificationMessagePayload

- src/auth/user-record.ts
- test/integration/auth.spec.ts
- test/unit/auth/user-record.spec.ts
It's returned from the server in a different format than the other timestamps.
Fixes #887
> fix(auth): Properly parse the lastRefreshTime.

- src/index.d.ts
- src/remote-config/remote-config-api-client.ts
- src/remote-config/remote-config.ts
- test/unit/remote-config/remote-config-api-client.spec.ts
- test/unit/remote-config/remote-config.spec.ts
- Add `rollback` operation to the RC API
Note: The API proposal is still under review. Getting a head start here.
> Add Remote Config Rollback operation

- test/integration/machine-learning.spec.ts
Backend changed the limit on the maximum number of characters in the displayName. Change tests to match.
> Fixing Firebase ML integration tests

- src/index.d.ts
- src/remote-config/remote-config-api-client.ts
- src/remote-config/remote-config.ts
- test/unit/remote-config/remote-config-api-client.spec.ts
- test/unit/remote-config/remote-config.spec.ts
- Add list versions operation
NOTE: Integration tests for all the new operations will be added in a separate PR.
> Remote Config Add list versions operation

- src/index.d.ts
- src/remote-config/remote-config-api-client.ts
- src/remote-config/remote-config.ts
- test/unit/remote-config/remote-config-api-client.spec.ts
- test/unit/remote-config/remote-config.spec.ts
- Add `getTemplateAtVersion()` for getting a RC template with a version number
- Revert `getTemplate()` to only access the active RC template of a project
- Add unit tests for `getTemplateAtVersion`
Note: All integration tests for go/admin-sdk-remote-config-change-history will be added in a separate PR
> Add a separate function for getting a Template with version number

- src/auth.d.ts
- src/auth/user-import-builder.ts
- test/integration/auth.spec.ts
I think there is an inconsistency with the defined `auth.d.ts` file [here](https://github.com/firebase/firebase-admin-node/blob/master/src/auth.d.ts#L802). This aims to add the interface to be consistent and then have an array of `UserProviderRequest`.
Similar change applies also for [metadata](https://github.com/firebase/firebase-admin-node/blob/master/src/auth.d.ts#L696).
Not sure if this is the best approach.
> fix(auth): Add interfaces for UserProviderRequest and Metadata used in UserImportRecord

- src/index.d.ts
- src/remote-config/remote-config-api-client.ts
- src/remote-config/remote-config.ts
- test/unit/remote-config/remote-config-api-client.spec.ts
- test/unit/remote-config/remote-config.spec.ts
- Add Version Metadata to Remote Config templates
- Exclude output only parameters from metadata in input templates
> Add version meta data to RC templates

- package-lock.json
- package.json
> fix: Upgraded node-forge and jsonwebtoken dependencies

- src/index.d.ts
- test/integration/auth.spec.ts
In the process of fixing this, also encountered 2 public types not currently exposed in our typings.
RELEASE NOTE: Added `GetUsersResult` and `DeleteUsersResults` interfaces to the exposed typings.
> fix(auth): Fixing flaky deleteUsers() integration tests

- src/auth/token-generator.ts
- test/unit/auth/token-generator.spec.ts
The iam.googleapis.com API that we use for signing JWTs is going away and being replaced by a new IAM service accounts API: https://cloud.google.com/iam/docs/migrating-to-credentials-api#blob
This PR migrates our existing code that relies on this endpoint.
> fix(auth): Migrated IAM sign endpoint to iamcredentials.googleapis.com

- src/index.d.ts
- src/remote-config/remote-config-api-client.ts
- src/remote-config/remote-config.ts
- test/unit/remote-config/remote-config-api-client.spec.ts
- test/unit/remote-config/remote-config.spec.ts
RELEASE NOTES: Added version management support for `admin.remoteConfig()` API. This API now supports `listVersions()`, `getTemplateAtVersion()`, and `rollback()` operations to help developers programmatically manage their Remote Config templates.
> feat(rc): Add Remote Config Version Management API

- src/remote-config/remote-config-api-client.ts
- src/remote-config/remote-config.ts
- test/integration/remote-config.spec.ts
- test/unit/remote-config/remote-config-api-client.spec.ts
- test/unit/remote-config/remote-config.spec.ts
- Add integration tests for `listVersions`, `getTemplateAtVersion`, and `rollback` operations
- Add integration tests for `versions` metadata in Remote Config templates
- Remove undefined values in list versions options, and add unit tests
- Check for empty versions lists in `listVersions`, and add unit tests
Note: Added `release:stage` to trigger integration tests. Merging to ~`remote-config-vc`~ `master`.
> Add integration tests for RC manage version operations

- src/firebase-app.ts
I noticed that the `databaseAuthVariableOverride` does not accept null in the source:
https://github.com/firebase/firebase-admin-node/blob/488f9318350c6b46af2e93b99907b9a02f170029/src/firebase-app.ts#L48-L56
Meanwhile, in typings it accepts null:
https://github.com/firebase/firebase-admin-node/blob/488f9318350c6b46af2e93b99907b9a02f170029/src/index.d.ts#L138-L163
Another observation is `object` vs `Object` discrepancy, from my understanding `object` is generally preferred but I don't know if it's safe or worth changing the typings for this.
> Add null to databaseAuthVariableOverride

- .github/workflows/ci.yml
- .github/workflows/release.yml
- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
- src/utils/api-request.ts
- test/integration/auth.spec.ts
Replaces scrypt npm module (no longer maintained and
doesn't work for node 12) for testing standard scrypt with
`crypto.scryptSync` which has been supported since node v10.5.
> Adds scrypt support in node 12

- .github/workflows/ci.yml
- package-lock.json
- package.json
Building on top of #739 this PR:
1. Upgrades `@google-cloud/firestore` to latest major version.
2. Adds Node 12 and 14 to CI matrix.
3. Bumped some typing dependencies to make the compiler happy.
API CHANGE: Admin SDK now requires Node.js 10 or higher. Node.js 8 support has been terminated.
API CHANGE: Upgraded dependency on the `@google-cloud/firestore` package to v4.
API CHANGE: Upgraded dependency on the `@google-cloud/storage` package to v5.
Resolves #934
> change: Dropped Node 8 support and upgraded Firestore/Storage dependencies

- package-lock.json
- package.json
As commnented on https://github.com/firebase/firebase-admin-node/pull/934#discussion_r452226525
Given that node-forge is a 0.x version, npm considers it to be a breaking change, and hence not compatible with the current requirement.
node-forge is also transitively being used by firestore (direct dependency is google-p12-pem), and requiring version ^0.9.0, which means two copies of the library are currently needed. Switching to just one dependency would save 1.7Mib.
If not, go file an issue about this **before creating a pull request** to …
> chore: update node-forge to ^0.9.1

- gulpfile.js
- src/auth/auth-api-request.ts
- src/database/database.ts
- src/firebase-namespace.ts
- src/machine-learning/machine-learning-api-client.ts
- src/messaging/messaging-api-request.ts
- src/project-management/project-management-api-request.ts
- src/remote-config/remote-config-api-client.ts
- src/security-rules/security-rules-api-client.ts
- src/utils/index.ts
- test/unit/auth/auth-api-request.spec.ts
- test/unit/firebase-namespace.spec.ts
- test/unit/machine-learning/machine-learning-api-client.spec.ts
- test/unit/messaging/messaging.spec.ts
- test/unit/project-management/project-management-api-request.spec.ts
- test/unit/remote-config/remote-config-api-client.spec.ts
- test/unit/security-rules/security-rules-api-client.spec.ts
- test/unit/utils/index.spec.ts
Removes instances of `XXX_SDK_VERSION_XXX` which were substituted by gulp at the build stage, and instead reads from `package.json` the value of `version`. 
Added unit test to verify that the value is read from `package.json`.
Edit: I had a thought of perhaps adding an integration test to it or for the `example.test.ts`, however this is a util function which isn't supposed to be exposed to developers hence my initial reaction was against that.
> chore: Remove instances of XXX_SDK_VERSION_XXX by reading version from package.json

- .eslintrc.js
Enabling the [keyword-spacing](https://eslint.org/docs/rules/keyword-spacing) rule which requires some spacing around keywords like `if` and `for`. No current violations detected.
> chore: Enable keyword-spacing ESLint rule

- src/auth/auth.ts
While working on auto-generated types for auth, I realized that there might be a missing conditional for `customUserClaims`.
In the typings:
https://github.com/firebase/firebase-admin-node/blob/92b0d37a6de9f19f6a625dbc4bc1a055b162622a/src/auth.d.ts#L1516
In the source:
https://github.com/firebase/firebase-admin-node/blob/92b0d37a6de9f19f6a625dbc4bc1a055b162622a/src/auth/auth.ts#L427
> fix(auth): Add null to customUserClaims inside BaseAuth.setCustomUserClaims

- package-lock.json
- package.json
- src/index.d.ts
- src/machine-learning/machine-learning-api-client.ts
- src/machine-learning/machine-learning.ts
- src/project-management/project-management-api-request.ts
- src/utils/api-request.ts
- test/integration/machine-learning.spec.ts
- test/unit/machine-learning/machine-learning-api-client.spec.ts
- test/unit/machine-learning/machine-learning.spec.ts
Add long running operation support
> FirebaseML - adding Long Running Operation support

- src/auth.d.ts
- src/database.d.ts
- src/index.d.ts
It is best-practice in TypeScript to use `object` instead of `Object`. While moving towards auto-generated typings, we will get this for free as the source was written correctly, however in the meantime this would make the move more transparent.
From my understanding this should be a safe move so-long as none of the developers use primitive types in place of Object (for example `Number`), but I don't think that is the case here. 
I provided more details in an internal document: go/firebase-admin-node-object
> fix: Use object instead of Object in typings

- src/auth/auth-config.ts
- src/auth/auth.ts
- src/auth/user-record.ts
- test/unit/auth/auth.spec.ts
- test/unit/auth/user-record.spec.ts
While working on the modularization of `instance-id` I came across several typing inconsistencies that I thought I'd bring up. Not sure if this is the best approach for all of them though.
Observation: The `enabled` field should not be optional in `auth-config.ts`.
Source
https://github.com/firebase/firebase-admin-node/blob/54a58348ab7d8ee5e1ef4fd90cb68110a3e41391/src/auth/auth-config.ts#L168-L170
Typing
https://github.com/firebase/firebase-admin-node/blob/54a58348ab7d8ee5e1ef4fd90cb68110a3e41391/src/auth.d.ts#L960-L972
Observation: There is a missing `uid` field in `DecodedIdToken`.
Source
https://github.com/firebase/firebase-admin-node/blob/54a58348ab7d8ee5e1ef4fd90cb68110a3e41391/src/auth/auth.ts#L108-L111
Typing
https://github.com/firebase/firebase-admin-node/blob/54a58348ab7d8ee5e1ef4 …
> fix(auth): Fix several typing inconsistencies

- src/auth.d.ts
The jsdoc for uid param of updateUser in auth.d.ts is wrong, it should be the uid to update instead of to delete.
Fix the wording of the uid param.
> Fix updateUser's typing jsdoc (delete => update)

- gulpfile.js
- package-lock.json
- package.json
The goal is to bridge the gap between today's Admin SDK (manually curated d.ts files, nested namespaces) and a modularized SDK that has auto-generated typings. To accomplish this, we can go forward with gradually refactoring the codebase to allow for auto-generated typings.
The first step is to modify the gulpfile to accommodate toggling between auto-generated types and the manually curated ones in the builds. For more information, view the internal document: go/firebase-node-auto-typing.
Depending on the value of `TYPE_GENERATION_MODE`:
- `TYPE_GENERATION_MODE = auto`: For all services that support auto-generated typings (i.e., have been refactored) the associated `d.ts` files are emitted. However, we automatically strip all files that have a suffix of `-internal.d.ts`, which is the …
> Modify gulpfile to allow for autogenerated types per-service

- src/auth.d.ts
- src/auth/auth-config.ts
There is a discrepancy regarding `displayName` being a mandatory field in `AuthProviderConfig`.
Source
https://github.com/firebase/firebase-admin-node/blob/031edc2c3eb3b676b95063ce33bfc5673d7dc2bc/src/auth/auth-config.ts#L29-L34
Typings
https://github.com/firebase/firebase-admin-node/blob/031edc2c3eb3b676b95063ce33bfc5673d7dc2bc/src/auth.d.ts#L1062-L1082
Assuming the typings are the source of truth I made it a mandatory field.
> fix(auth): Make displayName optional for AuthProviderConfig typings

- package-lock.json
- package.json
- src/index.d.ts
- src/machine-learning/machine-learning-api-client.ts
- src/machine-learning/machine-learning.ts
- test/integration/machine-learning.spec.ts
- test/unit/machine-learning/machine-learning-api-client.spec.ts
> Firebase ML - adding AutoML support

- package-lock.json
- src/machine-learning/machine-learning.ts
- test/unit/machine-learning/machine-learning.spec.ts
Firebase ML can gracefully ignore unknown fields in ModelResponse.
> Firebase ML can gracefully ignore unknown fields in ModelResponse

- src/index.d.ts
Just added a class that was missing from the Remote Config Namespace.
RELEASE NOTE: Added missing type definition for `ListVersionsOptions`.
> fix(rc): Add missing class in RemoteConfig Namespace

- src/auth.d.ts
- src/auth/auth.ts
- src/auth/user-import-builder.ts
- src/auth/user-record.ts
During my work for refactoring auth to auto-generate typings I came across several inconsistencies in source and typing files. I'm not sure how to best address them or which require changes, but I did an attempt here.
Observation: The `tenant` field is defined at the root of the object in the source while it's in the `firebase` scope in the typings.
Source:
https://github.com/firebase/firebase-admin-node/blob/5e6ebfa57649c425961351fbf772df4fead4f2f8/src/auth/auth.ts#L88-L112
Typing:
https://github.com/firebase/firebase-admin-node/blob/e415188c700a9ba8c2f3eac4fbf09ce598d095b4/src/auth.d.ts#L456-L491
Observation: The `SAMLAuthProviderConfig` contains an `enableRequestSigning` in the source which is absent in typings.
Source:
https://github.com/firebase/firebase-admin-node/blob/5e6ebfa57649c4 …
> fix(auth): Address several auth typing inconsistencies

- src/auth/token-generator.ts
- src/credential.d.ts
- src/credential/credential.ts
- src/credential/index.ts
- src/firebase-app.ts
- src/firebase-namespace.ts
- src/firestore/firestore-internal.ts
- src/index.d.ts
- src/storage/storage.ts
- src/utils/index.ts
- test/integration/setup.ts
- test/resources/mocks.ts
- test/unit/auth/auth.spec.ts
- test/unit/auth/token-generator.spec.ts
- test/unit/auth/token-verifier.spec.ts
- test/unit/credential/credential.spec.ts
- test/unit/firebase-app.spec.ts
- test/unit/firebase.spec.ts
- test/unit/firestore/firestore.spec.ts
- test/unit/index.spec.ts
- test/unit/utils/index.spec.ts
This pull request covers the following:
1. Splits the `index.d.ts` file which allows to substitute the typings (i.e., `index.d.ts` import for `credentials` will map to `src/credential.d.ts` or `src/credential/index.d.ts` depending on if auto-generated types are toggled).
- Note: This might introduce the duplicate "callable" bug in the documentation web-page
2. Refactors `credential.ts` to be a separate service outside of auth
3. Extracted the credentials related component of `auth/*.spec.ts` into new unit test folder `credential/*.spec.ts`
4. Adds documentation for auto-generated typings, as part of #992
> auth: Add credential service

- README.md
- gulpfile.js
- src/database/index.ts
- src/firebase-app.ts
- src/firebase-namespace-api.ts
- src/firebase-namespace.d.ts
- src/firebase-namespace.ts
- src/firestore/index.ts
- src/instance-id/index.ts
- src/messaging/index.ts
- src/project-management/index.ts
- src/remote-config/index.ts
- src/security-rules/index.ts
- src/storage/index.ts
- src/utils/index.ts
- test/integration/setup.ts
- test/resources/mocks.ts
- test/unit/utils.ts
- test/unit/utils/index.spec.ts
* Declared APIs of top-level admin namespace members:
- FirebaseError
- FirebaseArrayIndexError
- AppOptions
- app (namespace/function)
- App
- SDK_VERSION
- initializeApp
- apps
* Implemented the `app.App` interface in the `FirebaseApp` class.
* Using the same `AppOptions` type across the repo.
> chore: Declared admin and admin.app namespaces

- gulpfile.js
- src/firebase-namespace-api.ts
- src/firebase-namespace.d.ts
- src/instance-id/index.ts
- src/instance-id/instance-id.ts
* Exposed `admin.instanceId` namespace.
* Exposed `App.instanceId()` method.
> chore(iid): Exposed admin.instanceId namespace

- gulpfile.js
- src/auth/action-code-settings-builder.ts
- src/auth/auth-api-request.ts
- src/auth/auth-config.ts
- src/auth/auth.ts
- src/auth/identifier.ts
- src/auth/index.ts
- src/auth/tenant-manager.ts
- src/auth/tenant.ts
- src/auth/token-verifier.ts
- src/auth/user-import-builder.ts
- src/auth/user-record.ts
- src/firebase-namespace-api.ts
- src/firebase-namespace.d.ts
- test/integration/auth.spec.ts
- test/unit/auth/auth-api-request.spec.ts
- test/unit/auth/auth-config.spec.ts
- test/unit/auth/auth.spec.ts
- test/unit/auth/tenant-manager.spec.ts
- test/unit/auth/tenant.spec.ts
- test/unit/auth/user-import-builder.spec.ts
* Exposed `admin.auth` namespace and the `App.auth()` method.
* The public `SAMLAuthProviderConfig` doesn't support `enableRequestSigning` although the implementation does. Needed some minor changes in the implementation and the tests to reconcile this.
* `TenantOptions` type only exists in the implementation. In the public API this is `UpdateTenantRequest`. Needed some changes to reconcile this.
Part of the go/firebase-node-one-source effort.
> chore(auth): Exposed admin.auth namespace

- README.md
- gulpfile.js
- src/firebase-app.ts
- src/firebase-namespace.ts
- src/firebase-service.ts
- test/resources/mocks.ts
- test/unit/firebase-app.spec.ts
- test/unit/firebase-namespace.spec.ts
- test/unit/firebase.spec.ts
* Using the public `App` type in `AppHook`, `FirebaseNamespace` and `FirebaseServiceInterface` types.
* Configured the gulpfile to copy all `**/index.d.ts` files to the output except `utils/index.d.ts` which is internal.
> chore: Using public API types in FirebaseNamespace impl

- package-lock.json
- package.json
- src/auth/auth-api-request.ts
- src/auth/auth.ts
- src/auth/token-generator.ts
- src/auth/token-verifier.ts
- test/resources/mocks.ts
- test/unit/auth/auth.spec.ts
- test/unit/auth/token-generator.spec.ts
- test/unit/auth/token-verifier.spec.ts
For Googlers: [this design doc](https://docs.google.com/document/d/1EDQh305tKokFU8A_A9G4SPQBhappt-TkUMLRI9tyBFE/edit?usp=sharing) explains the behavior changes and security implications.
N/A
> Add support for Auth Emulator

- README.md
- docgen/content-sources/node/toc.yaml
- docgen/generate-docs.js
- src/auth/index.ts
- src/credential/index.ts
- src/database/index.ts
- src/firebase-namespace-api.ts
- src/instance-id/index.ts
- src/machine-learning/index.ts
- src/messaging/index.ts
- src/messaging/messaging.ts
- src/project-management/android-app.ts
- src/project-management/index.ts
- src/project-management/project-management.ts
- src/remote-config/index.ts
- src/remote-config/remote-config.ts
- src/security-rules/index.ts
- src/security-rules/security-rules.ts
- src/storage/index.ts
Single API Extractor/API Documenter integration can take a while, I'm fixing our existing TypeDoc pipeline to work with the auto-generated typings.
* Updated the API docs generator to run against auto-generated d.ts files in the `lib/` directory.
* Updated the affected TOC entries.
* Adding RTDB type aliases to the generated HTML (in a manner similar to how Firestore type aliases are handled)
* Fixed a bunch of broken cross links.
* Defined `Database` as a type that extends the `@firebase/database` package, as opposed to using module augmentation. TypeDoc generates a much better HTML output for RTDB types with this change.
Preview at cl/336354281
> chore: Updated TypeDoc workflow to generate API docs

- test/integration/typescript/tsconfig.json
- tsconfig.json
Latest versions of GCP dependencies like Firestore require `es2018` libraries included in the tsc build. This helps avoid build errors like https://github.com/firebase/firebase-admin-node/actions/runs/342357542
> fix: Adding es2018 libraries to the build

- package-lock.json
- package.json
- src/firestore/index.ts
- test/integration/firestore.spec.ts
RELEASE NOTE: Exposed a series of new Firestore SDK types from the `admin.firestore` namespace. Newly exposed types include `GrpcStatus`, `FirestoreDataConverter`, `UpdateData` and more.
RELEASE NOTE: Upgraded the Firestore SDK version to v4.5.0 and higher.
Resolves #1064 
Resolves #1074
> feat(firestore): Exposed more types from the admin.firestore namespace

- src/remote-config/remote-config.ts
- test/unit/remote-config/remote-config.spec.ts
- Current check for update time fails for timestamps with more than 3 milliseconds places. Updated the timestamp validation logic as a quick fix.
Resolves: #1088
> fix(rc): Fix Version update time parsing failure

- etc/firebase-admin.api.md
- src/messaging/index.ts
`ApnsPayload` can contain any valid JSON values.
Resolves #1023
> fix(fcm): Support arbitrary custom values in the ApnsPayload

- src/remote-config/remote-config.ts
- test/unit/remote-config/remote-config.spec.ts
- Add unit test for timestamps with 9 digits in fractional seconds
- Code cleanup
> chore(rc): Add more unit tests for timestamp validation

- etc/firebase-admin.api.md
- gulpfile.js
- src/app/firebase-app.ts
- src/instance-id/index.ts
- src/instance-id/instance-id-request-internal.ts
- src/instance-id/instance-id.ts
- src/utils/index.ts
- test/unit/index.spec.ts
- test/unit/instance-id/index.spec.ts
- test/unit/instance-id/instance-id.spec.ts
* Added `instanceId()` module-level function.
* Added `firebase-admin/instance-id` module.
> feat: Added instanceId() modularized API

- etc/firebase-admin.api.md
- src/app/core.ts
- src/app/credential-factory.ts
- src/app/credential-internal.ts
- src/app/credential.ts
- src/app/firebase-app.ts
- src/app/firebase-namespace.ts
- src/app/index.ts
- src/auth/token-generator.ts
- src/credential/index.ts
- src/firestore/firestore-internal.ts
- src/storage/storage.ts
- src/utils/index.ts
- test/resources/mocks.ts
- test/unit/app/credential-internal.spec.ts
- test/unit/app/firebase-app.spec.ts
- test/unit/app/firebase-namespace.spec.ts
- test/unit/app/index.spec.ts
- test/unit/auth/auth.spec.ts
- test/unit/auth/token-generator.spec.ts
- test/unit/auth/token-verifier.spec.ts
- test/unit/firebase.spec.ts
- test/unit/firestore/firestore.spec.ts
- test/unit/index.spec.ts
- test/unit/utils/index.spec.ts
* Exposed `ServiceAccount`, `GoogleOAuthAccessToken`, `cert()`, `applicationDefault()` and `refreshToken()` APIs from the `app` submodule.
* Moved credential implementations under the same submodule.
* Aliased the new APIs from the existing `admin.credential` namespace for backward compatibility.
> feat: Moved the credential APIs under firebase-admin/app

- src/utils/error.ts
FireabseErrorInterface -> FirebaseErrorInterface
> update typo in interface name

- etc/firebase-admin.api.md
- src/app/firebase-app.ts
- src/auth/auth-namespace.ts
- src/auth/index.ts
- src/instance-id/index.ts
- test/unit/auth/index.spec.ts
- test/unit/index.spec.ts
* Renaming the service accessor functions to be consistent with the approved API proposal.
* Added some unit tests for the `getAuth()` function.
> fix: Renaming service functions to getAuth and getInstanceId

- etc/firebase-admin.api.md
- gulpfile.js
- src/app/firebase-app.ts
- src/database/database.ts
- src/database/index.ts
- test/unit/database/database.spec.ts
- test/unit/database/index.spec.ts
- test/unit/index.spec.ts
* Added `getDatabase()` and `getDatabaseWithUrl()` entry functions.
* Exported `Database` type with the methods for managing security rules.
* Exported other public interface types from `@firebase/database-types` package.
* Exported `enableLogging` and `ServerValue` members from the `@firebase/database` package.
> feat(rtdb): Added firebase-admin/database module entrypoint

- package-lock.json
- package.json
- src/auth/auth-api-request.ts
- src/auth/auth.ts
- src/auth/token-verifier.ts
- test/integration/auth.spec.ts
- test/integration/setup.ts
- test/unit/auth/auth.spec.ts
- test/unit/auth/token-verifier.spec.ts
This PR implements http://go/firebase-auth-emulator-admin-sdk (Google internal design doc). Token verification now works everywhere, not just in functions emulator.
Ran `node ~/w/firebase-tools/lib/bin/firebase.js emulators:exec --project fake-project-id --only auth 'npx mocha test/integration/auth.spec.ts --slow 5000 --timeout 20000 --require ts-node/register'` manually and all tests passed locally (once unrelated pending fixes in the Auth Emulator such as https://github.com/firebase/firebase-tools/pull/3091 and https://github.com/firebase/firebase-tools/pull/3088 are applied).
(secret API removed; no public API changes)
> Improve token verification logic with Auth Emulator.

- docgen/generate-docs.js
* Typedoc 0.19.x generates 2 additional sections for `admin.firestore` and `admin.database` namespaces that have type re-exports. This PR updates the doc generator script to programmatically remove them from the HTML output.
* Also disabling link generation for several Firestore types that do not have separate external documentation.
> chore: Updated doc generator for typedoc 0.19.0

- etc/firebase-admin.api.md
- etc/firebase-admin.app.api.md
- etc/firebase-admin.instance-id.api.md
- src/app/core.ts
- src/app/credential-factory.ts
- src/app/credential.ts
- src/app/lifecycle.ts
- src/instance-id/index.ts
- src/instance-id/instance-id.ts
Added documentation for `firebase-admin/app` and `firebase-admin/instance-id` module entry points. For the most part I'm copying the existing documentation from our main branch. Note that the API report indicates the docs status of each API.
> fix: Updated documentation for app and instance-id entry points

- etc/firebase-admin.auth.api.md
- src/auth/auth-config.ts
- src/auth/auth-namespace.ts
- src/auth/auth.ts
- src/auth/base-auth.ts
- src/auth/identifier.ts
- src/auth/tenant-manager.ts
- src/auth/tenant.ts
- src/auth/token-verifier.ts
- src/auth/user-record.ts
* Updated documentation for public APIs. Documentation text copied from the current main branch.
* Changed `BaseAuth` into an abstract class.
> fix(auth): Updated API docs for firebase-admin/auth

- etc/firebase-admin.database.api.md
- etc/firebase-admin.machine-learning.api.md
- etc/firebase-admin.messaging.api.md
- etc/firebase-admin.project-management.api.md
- etc/firebase-admin.remote-config.api.md
- etc/firebase-admin.security-rules.api.md
- etc/firebase-admin.storage.api.md
- src/database/index.ts
- src/machine-learning/index.ts
- src/machine-learning/machine-learning.ts
- src/messaging/index.ts
- src/messaging/messaging.ts
- src/project-management/android-app.ts
- src/project-management/index.ts
- src/project-management/ios-app.ts
- src/remote-config/index.ts
- src/remote-config/remote-config.ts
- src/security-rules/index.ts
- src/security-rules/security-rules.ts
- src/storage/index.ts
- src/storage/storage.ts
Added missing API docs to the remaining modules.
> fix: Updated API docs of remaining modules

- test/integration/app.spec.ts
- test/integration/auth.spec.ts
- test/integration/database.spec.ts
- test/integration/firestore.spec.ts
- test/integration/instance-id.spec.ts
- test/integration/machine-learning.spec.ts
- test/integration/messaging.spec.ts
- test/integration/project-management.spec.ts
- test/integration/remote-config.spec.ts
- test/integration/security-rules.spec.ts
- test/integration/setup.ts
- test/integration/storage.spec.ts
I've updated the existing integration test suite to use the new modular API surface whenever possible. Most of the changes required were pretty straightforward. For example:
1. Changing invocations like `admin.auth()` into `getAuth()`.
2. Changing type annotations like `admin.auth.UserRecord` into `UserRecord`.
However, this change broke some of the existing lazy loading tests. The updated `database.spec.ts` and `firestore.spec.ts` imports `firebase-admin/database` and `firebase-admin/firestore`, which in turn loads the corresponding 3rd party dependencies. The old lazy loading tests relied on this not happening. I've implemented a somewhat hacky solution to get around this issue. But we should probably find a better way to test lazy loading in the future.
> fix: Updated integration tests to use the modular API surface

- src/database/database-internal.ts
- test/unit/database/database.spec.ts
Connect to the emulator in `getRules()` and `setRules()` APIs when the emulator mode is enabled. Emulator mode can be enabled by setting the `FIREBASE_DATABASE_EMULATOR_HOST` env variable, or by setting an emulator URL directly in AppOptions. In the first case we pick up the namespace from the `databaseURL` App option.
Resolves #1149 
RELEASE NOTE: Rules management APIs now support the Firebase emulator suite. Methods like `getRules()` and `setRules()` will automatically connect to the local emulator, when the emulator mode is enabled.
> feat(rtdb): Support emulator mode for rules management operations

- src/database/database-internal.ts
- test/unit/database/database.spec.ts
#1194 has introduced a regression that is causing an [integration test failure](https://github.com/firebase/firebase-admin-node/actions/runs/668209320):
```
Error: Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "Cannot read property 'appInternal' of undefined".
at FirebaseAppError.FirebaseError [as constructor] (lib/utils/error.js:44:28)
at FirebaseAppError.PrefixedFirebaseError [as constructor] (lib/utils/error.js:90:28)
at new FirebaseAppError (lib/utils/error.js:125:28)
at /home/runner/work/firebase-admin-node/firebase-admin-node/lib/firebase-app.js:81:19
at process._tickCallback (internal/process/next_tick.js:68:7)
```
This is because we are registering an instance method …
> fix(rtdb): Fixing the RTDB token listener callback

- .github/actions/send-email/dist/index.js
- .github/actions/send-email/index.js
- .github/workflows/nightly.yml
- The script was failing because the `domain` was undefined in the script (it should be `config.domain`).
- This PR fixes the above issue and instead of passing the whole config object this includes only the necessary parameters in the message.
> chore: Fix bug in send-email action code

- .github/workflows/nightly.yml
- Change dispatch event name to `firebase_nightly_build`
> Change dispatch event name in nightly workflow

- test/integration/remote-config.spec.ts
- Remove the failing integration test that was added to trigger the send email workflow in nightly builds.
- The test was added in #1210 
- Nightly workflow tests were completed at:
- https://github.com/firebase/firebase-admin-node/actions/runs/709407686
- https://github.com/firebase/firebase-admin-node/actions/runs/709427014
> chore: Clean up nightly workflow trigger tests

- etc/firebase-admin.auth.api.md
- src/auth/user-record.ts
- test/unit/auth/user-record.spec.ts
Discovered a couple of deviations in the new API when compared to the existing API surface.
* `UserMetadata.lastRefreshTime` should be optional
https://github.com/firebase/firebase-admin-node/blob/d961c3f705a8259762a796ac4f4d6a6dd0992eb1/src/auth/index.ts#L64
* `MultiFactorSettings.toJSON` should return `object`
https://github.com/firebase/firebase-admin-node/blob/d961c3f705a8259762a796ac4f4d6a6dd0992eb1/src/auth/index.ts#L311
> fix(auth): Fixing some public API signatures to be consistent with the current API

- package.json
Setting the version on the modular-sdk branch to 9.100.0-alpha.0. These artifacts will be published to a separate NPM tag, so will not conflict with our official releases.
> Version bumped to alpha0 release

- test/integration/auth.spec.ts
Reverts firebase/firebase-admin-node#1205
Bug in emulator has been fixed in the latest release. Safe to merge if CI passes.
> Revert "Disable one flaky tests in emulator."

- src/database/database-internal.ts
- src/firebase-app.ts
- test/unit/database/database.spec.ts
Resolves #1231 and #1233
We originally assumed that a credential would never issue tokens with a TTL shorter than 5 minutes. But turns out this assumption does not hold in the latest GCF runtime, where the metadata server can issue tokens with TTLs as short as 2 minutes. In such situations the SDK ends up in a livelock resulting in high CPU/memory usage, and other normal operations timing out.
Livelock event sequence:
1. Attempt to fetch a new token: the metadata server sends a token with a TTL less than 5 minutes.
2. Fire token change listeners.
3. RTDB token change listener calls `FirebaseApp.INTERNAL.getToken()` to access the last fetched token.
4. But the last fetched token has a TTL less than 5 minutes (i.e. eligible for refresh). Back to step 1.
In order to break the above cycle, …
> fix(rtdb): Fixing a token refresh livelock in Cloud Functions

- etc/firebase-admin.api.md
- src/firebase-namespace-api.ts
`App` is exposed via the `admin.app` namespace. Not necessary to expose it on the `admin` namespace too.
> fix: Removed App from the top-level admin namespace

- src/utils/error.ts
Catch `EMAIL_NOT_FOUND` and translate to `auth/email-not-found` when `/accounts:sendOobCode` is called for password reset on a user that does not exist.
Fixes https://github.com/firebase/firebase-admin-node/issues/1202
> fix(auth): adds missing EMAIL_NOT_FOUND error code

- etc/firebase-admin.api.md
- etc/firebase-admin.database.api.md
- etc/firebase-admin.firestore.api.md
- package-lock.json
- package.json
- src/auth/auth-namespace.ts
- src/database/database-namespace.ts
- src/database/database.ts
- src/database/index.ts
- src/firestore/index.ts
- src/instance-id/instance-id-namespace.ts
- src/machine-learning/machine-learning-namespace.ts
- src/messaging/messaging-namespace.ts
- src/project-management/project-management-namespace.ts
- src/remote-config/remote-config-namespace.ts
- src/security-rules/security-rules-namespace.ts
- src/storage/storage-namespace.ts
Added docstrings referencing the source of truth definitions in new module entrypoints. For example, the `admin.auth.UserRecord` type alias gets a docstring with a reference to the `UserRecord` export in the `firebase-admin/auth` module entry point. These references are correctly converted into hyperlinkg by API Documenter.
> chore: Added docstrings to type aliases in namespaces

- src/storage/storage.ts
- test/unit/storage/storage.spec.ts
The Firebase style env var for storage emulator can't have protocol and the Cloud version *must* have a protocol.
> Fix storage emulator env formatting

- src/app-check/app-check-api-client-internal.ts
- src/app-check/token-generator.ts
- src/app-check/token-verifier.ts
- test/integration/app-check.spec.ts
- test/unit/app-check/app-check-api-client-internal.spec.ts
- test/unit/app-check/token-generator.spec.ts
- Update to beta
- Add integration test for verify token api
> chore: Update FAC to beta

- package-lock.json
- package.json
- src/utils/api-request.ts
Upgraded the `@types/node` dependency to v12.12.47
> Fix @types/node conflict with grpc and port type

- docgen/post-process.js
* Updated dotted module names like `firebase-admin.auth` to the correct `firebase-admin/auth` form.
* Replaces the work "package" with "module" for accuracy.
Preview home page: https://github.com/firebase/firebase-admin-node/blob/modular-sdk-docs/docgen/markdown/index.md
> chore: Added post processing script to fix doc titles and links

- src/auth/auth-api-request.ts
- test/unit/auth/auth-api-request.spec.ts
MFA `uid` should be optional for `updateUser` operations.
When not specified, the backend will provision a `uid` for the
enrolled second factor.
Fixes https://github.com/firebase/firebase-admin-node/issues/1276
> fix(auth): make MFA uid optional for updateUser operations

- package-lock.json
- package.json
We no longer seem to use this dependency. Likely because we switched to reading the package version from the `package.json` file, as opposed to writing it to source files during build time.
> chore: Remove gulp-replace dependency

- test/integration/messaging.spec.ts
The backend server has implemented a behavior change that is causing this test to fail. Temporarily disabling the test as we work with the FCM team to understand the new behavior, and incorporate it into our implementation correctly.
> chore: Temporarily disabling sendToDeviceGroup integration test

- etc/firebase-admin.api.md
- etc/firebase-admin.app.api.md
- etc/firebase-admin.auth.api.md
- etc/firebase-admin.database.api.md
- etc/firebase-admin.firestore.api.md
- etc/firebase-admin.instance-id.api.md
- etc/firebase-admin.machine-learning.api.md
- etc/firebase-admin.messaging.api.md
- etc/firebase-admin.project-management.api.md
- etc/firebase-admin.remote-config.api.md
- etc/firebase-admin.security-rules.api.md
- etc/firebase-admin.storage.api.md
- src/app/index.ts
- src/auth/index.ts
- src/database/index.ts
- src/default-namespace.d.ts
- src/firestore/index.ts
- src/instance-id/index.ts
- src/machine-learning/index.ts
- src/messaging/index.ts
- src/project-management/index.ts
- src/remote-config/index.ts
- src/security-rules/index.ts
- src/storage/index.ts
Preview: https://github.com/firebase/firebase-admin-node/blob/modular-sdk-docs/docgen/markdown/index.md
> chore: Added package docs for module entry points

- src/auth/index.ts
- Update reference docs for `OAuthResponseType` suggested in: https://github.com/firebase/firebase-admin-node/pull/1220/files/0a0cd0dbb94279a28acd96c44094f364a00e20c7#r630566106
> Update OIDC reference docs

- docgen/post-process.js
- package-lock.json
- package.json
Generating a TOC using the latest API Documenter fork shipped by the JS SDK team.
Sample output: https://github.com/firebase/firebase-admin-node/blob/modular-sdk-docs/docgen/markdown/toc.yaml
> chore: Added support for generating a toc file for docs

- docgen/generate-docs.js
> fix(docs): replace all global.html -> admin.html

- docgen/content-sources/node/toc.yaml
Adding the new `Base*` types introduced in #1294 to the TOC. The type aliases are documented in the `admin.auth` page, and do not require separate TOC entries.
> fix: Updated TOC for new Auth type aliases

- gulpfile.js
`npm run build` etc. will now copy over the the `.d.ts` and `.json` files found in `generated/messaging`. Before, this didn't happen, and the generated client would error on runtime.
> Update Gulpfile to copy files required for generated client to properly run

- etc/firebase-admin.api.md
- src/app-check/app-check.ts
- src/app-check/index.ts
- src/app-check/token-generator.ts
- src/messaging/messaging-internal.ts
- src/utils/index.ts
- test/integration/app-check.spec.ts
- test/unit/app-check/app-check.spec.ts
- test/unit/app-check/token-generator.spec.ts
- test/unit/utils/index.spec.ts
- Add new `AppCheckTokenOptions` type
- Change the public API `createToken(...)` to accept optional `AppCheckTokenOptions`
- Add validations for custom `ttl`
- Move `transformMillisecondsToSecondsString()` to `utils`
- Add unit tests. ~(Integration tests will follow in a separate PR)~
- Add integration tests.
RELEASE NOTE: The `createToken()` API now supports configuring the `TTL` of the returned Firebase App Check Token.
> feat(fac): Add custom TTL options for App Check

- src/app-check/token-generator.ts
- test/unit/app-check/token-generator.spec.ts
Reduce custom token expiration down to 5 minutes.
> fix: Reduce App Check custom token exp to 5 mins

- .github/workflows/nightly.yml
- Run emulator based integration tests as part of the nightly tests.
> chore: Add emulator tests to nightlies

- etc/firebase-admin.api.md
- src/auth/auth.ts
- src/auth/index.ts
Update the comment in index.ts for VerifyIdToken and VerifySessionCookie be same as in auth.ts.
> fix: Update comments in index files

- etc/firebase-admin.api.md
- src/remote-config/index.ts
- test/integration/remote-config.spec.ts
- test/unit/remote-config/remote-config-api-client.spec.ts
- test/unit/remote-config/remote-config.spec.ts
go/admin-sdk-rc-parameter-value-types
- Add RC Parameter Value Type.
- Update unit tests.
~- Integration tests will be added following the REST API launch.~
- Added `release:stage` to trigger existing integration tests (to test backward compatibility).
~- `Do not merge` until the BE is updated.~
Update:
- Integration tests are updated.
RELEASE NOTE: Added Remote Config Parameter Value Type Support.
> feat(rc): Add Remote Config Parameter Value Type Support

- etc/firebase-admin.app.api.md
- src/app/firebase-app.ts
- src/app/firebase-namespace.ts
- src/app/lifecycle.ts
- src/default-namespace.ts
- src/instance-id/instance-id.ts
- test/resources/mocks.ts
- test/unit/app/firebase-app.spec.ts
- test/unit/app/firebase-namespace.spec.ts
- test/unit/app/index.spec.ts
- test/unit/firebase.spec.ts
- test/unit/utils.ts
Currently, the `firebase-admin/app` entry point is implemented on top of a `FirebaseNamespace` instance. Top-level functions like `initializeApp()` simply delegate to the `FirebaseNamespace.initializeApp()` method. Since `FirebaseNamespace` has dependencies on all other services exposed within the SDK, importing `firebase-admin/app` can pull in other services as well. This is quite evident when we try to bundle the SDK using a tool like webpack:
**webpack.js**
```
const path = require('path');
module.exports = {
target: "node",
entry: {
app: ["./src/index.js"]
},
output: {
path: path.resolve(__dirname, "dist"),
filename: "index.js"
},
};
```
**src/index.js**
```
import { initializeApp } from "firebase-admin/app";
initializeApp();
```
Bundling the above source file with webpack yields the …
> fix: Decoupled FirebaseNamespace from new module entry points

- package-lock.json
- package.json
In `@types/jsonwebtoken@8.5.5` the data type of the property `header` is [changed](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53435/files#r699621093) from `header: object` to `header: JWTHeader`. This change results in type errors in our test build.
This PR pins the `@types/jsonwebtoken` to version `8.5.1` as a short term fix.
Internal issue to track b/200963946
> Pin @types/jsonwebtoken to 8.5.1

- gulpfile.js
- package-lock.json
- package.json
- src/database/database-internal.ts
- src/database/index.ts
- src/firebase-namespace.ts
- test/integration/app.spec.ts
- test/integration/auth.spec.ts
- test/unit/app-check/token-generator.spec.ts
- test/unit/firebase-namespace.spec.ts
- test/unit/utils/jwt.spec.ts
The `@firebase/database` package now exposes the modular API since the v9 JS SDK release. Admin SDK should upgrade to the latest dependencies, using the `@firebase/database-compat` package as the new intermediary. @Feiyang1 is working on some changes in the JS SDK side to make this work smoothly.
RELEASE NOTE: Refactored the `admin.database()` API to use the new `@firebase/database-compat` package under the hood. This helps avoid several dependency conflicts, and type compilation errors when using Firebase Web SDK packages alongside the Admin SDK.
> fix(rtdb): Changed admin.database to use database-compat package

- src/utils/jwt.ts
- test/unit/utils/jwt.spec.ts
- Change the jwks cache duration (used by the verify token API) from 1 day to 6 hours.
- b/200973487
> fix(fac): Change the jwks cache duration from 1 day to 6 hours

- docgen/post-process.js
Our API doc post processing script currently writes line endings with `\r\n`. Apparently devsite doesn't like that. Just using `\n` which seems to be acceptable to the devsite publishing tools.
> fix: Remove CR (\r) from generated content

- src/utils/error.ts
- test/integration/auth.spec.ts
Add disabled error code, to avoid unparsed internal error in createSessionCookie(). see [issue](https://github.com/firebase/firebase-admin-node/issues/1503)
> fix(auth): Add user disabled error code.

- package-lock.json
- package.json
- test/integration/auth.spec.ts
- test/unit/auth/tenant.spec.ts
- test/unit/security-rules/security-rules.spec.ts
This is the second PR of a series of changes to update @google-cloud/firestore dependency to 5.x. This is a follow-up to #1540 
- Upgraded Typescript from ~3.7.3 to ~4.4.3
- Fixed `TS2790: The operand of a 'delete' operator must be optional` errors
**Note:** Manually tested for backwards compatibility on TS 3.7.x to 4.5.x. We will add TS compatibility tests to CIs in the future.
> chore: Update Typescript to 4.x

- etc/firebase-admin.api.md
- package-lock.json
- package.json
- src/firestore/firestore-namespace.ts
This PR resolves #1524  
An update to typescript is also included in the PR to resolve the compilation error that occurs in Google-cloud/firestore.
> version update @google-cloud/firestore to 5.x

- package.json
Reverts firebase/firebase-admin-node#1553
It appears that the TS4 upgrade (required for Firestore upgrade) breaks backwards compatibility with `tsc 3.x` (caught during the release process). Reverting this until we investigate the best path forward.
> Revert "[chore] Release 10.1.0"

- etc/firebase-admin.auth.api.md
- src/auth/auth-api-request.ts
- src/auth/auth-config.ts
- src/auth/auth.ts
- src/auth/index.ts
- src/auth/project-config-manager.ts
- src/auth/project-config.ts
- src/auth/tenant.ts
- src/utils/error.ts
- test/unit/auth/project-config-manager.spec.ts
- test/unit/auth/project-config.spec.ts
Recaptcha config changes in project config.
- Implemented getProjectConfig.
- Implemented updateProjectConfig.
- Updated error code.
> Project config - Recaptcha config

- test/integration/auth.spec.ts
Integration test for UpdateTenant, getProjectConfig, updateProjectConfig on reCAPTCHA config.
Tests ran passed against a real project.
> Recapcha integ test

- package.json
- Bumped the `node-forge` version to `1.3.1`
> chore: Updating node-forge to 1.3.1

- etc/firebase-admin.api.md
- etc/firebase-admin.auth.api.md
- src/auth/auth-namespace.ts
- src/auth/base-auth.ts
- src/auth/index.ts
- src/auth/token-verifier.ts
- src/utils/error.ts
- test/resources/mocks.ts
- test/unit/auth/auth.spec.ts
- test/unit/auth/token-verifier.spec.ts
```
const decoded = await firebase.getAuth()._verifyAuthBlockingToken(token, audience);
```
> Adding in alpha interface for blocking token verification

- etc/firebase-admin.auth.api.md
- src/auth/auth-api-request.ts
- src/auth/base-auth.ts
- src/utils/error.ts
- test/integration/auth.spec.ts
- test/unit/auth/auth-api-request.spec.ts
- test/unit/auth/auth.spec.ts
Support generate email link for VERIFY_AND_CHANGE_EMAIL action.
> feat(auth): Support generate oob code request type VERIFY_AND_CHANGE_EMAIL

- src/app-check/app-check-api-client-internal.ts
- src/app-check/token-generator.ts
- src/app-check/token-verifier.ts
- test/unit/app-check/app-check-api-client-internal.spec.ts
- test/unit/app-check/token-generator.spec.ts
- Change App Check endpoints to V1
b/228179692
> chore: Update App Check to V1 endpoints

- etc/firebase-admin.auth.api.md
- src/auth/auth-config.ts
- src/utils/error.ts
- test/integration/auth.spec.ts
- test/unit/auth/project-config.spec.ts
- test/unit/auth/tenant.spec.ts
Added account defender support as reCAPTCHA add-on feature.
Added additional integration tests for this feature.
> Account defender support for reCAPTCHA

- src/auth/auth-config.ts
- src/auth/project-config-manager.ts
- src/auth/project-config.ts
- src/auth/tenant.ts
This PR include the changes addressing tech review feedback.
comments are extract from PR https://github.com/firebase/firebase-admin-node/pull/1603
> Address recaptcha tech review feedback

- src/eventarc/eventarc.ts
- src/functions/functions-api.ts
- src/functions/functions.ts
Fix markdown lists in reference docs.
Note: It appears that TSDoc can't parse markdown lists in the description yet.
> Fix markdown lists in reference docs

- package.json
> fix: Add type declarations to exports fields

- README.md
- package.json
- Includes fixes for #1512, #1718, and #1726
- Node.js 12 support is deprecated. We strongly encourage you to use Node.js 14 or higher as we will drop support for Node.js 12 in the next major version. We will also upgrade Typescript to 4.x in the next major version.
> [chore] Release 10.3.0

- .github/workflows/ci.yml
- package.json
- test/unit/machine-learning/machine-learning.spec.ts
- Bumped version to 11.0.0
- Fixed ML unit tests to pass on Node 16.
- The error message is different on Node 14 vs 16 `Cannot read properties of null (reading 'done')` vs  `Cannot read property 'done' of null`
- Updated to only check for rejection instead of checking for an exact error string.
- Added Node 16 to CI
Breaking change: Dropped support for Node.js 12. Developers should use Node.js 14 or higher when deploying the Admin SDK.
Breaking change: Upgraded TypeScript to [v4.6.4](https://github.com/microsoft/TypeScript/releases/tag/v4.6.4).
Breaking change: Upgraded the @google-cloud/firestore package to v5. This contains breaking changes. Refer to the Cloud Firestore [release notes](https://github.com/googleapis/nodejs-firestore/releases/tag/v5.0.0) for more details.
Breaking change: …
> [chore] Release 11.0.0

- src/app/credential-internal.ts
- src/functions/functions-api-client-internal.ts
Realized that I never actually pushed the commit containing the requested fixes from #1812 🤦
> PR fixes from #1812

- package-lock.json
- package.json
- Updated `@firebase/api-documenter` to `v0.2.0`
- Added `--project admin` to generate correct headers for devsite
> chore: Update api-documenter config to include project headers

- src/messaging/messaging-api-request-internal.ts
- test/unit/messaging/messaging.spec.ts
- Increase the FCM timeout to 15s to match the recommended timeout in the BE. This will prevent duplicate notifications due to the Admin SDK retrying too early.
Fixes: #1900
> fix(fcm): Increase FCM timeout to 15s

- etc/firebase-admin.firestore.api.md
- src/firestore/index.ts
**ReadWriteTransactionOptions**  is not exported from `firebase-admin/firestore` however available in `@google-cloud/firestore`
> fix(firestore): added missing 'ReadWriteTransactionOptions' export (#1874)

- src/extensions/extensions-api.ts
- src/extensions/extensions.ts
> Extensions TSDoc edits

- src/utils/api-request.ts
- test/integration/auth.spec.ts
Hey there,
after updating our application to node 19 we noticed that the firebase package is causing a `MaxListenersExceededWarning` error. The error occurs in the underlying method call in `HttpClient.send` namely in `AsyncHttpCall.execute`. There the timeout listener is not removed after the socket is closed. I could provoke the error only in the integration tests, in the unit tests to the mentioned method the error does not occur. Therefore I added a listener spy check in the `afterEach` of the auth integration tests which should not be called. 
Attention, the error only occurs with Node 19, if someone wants to test the behavior it must be done with this version.
Thanks for the great work – I am looking forward to your review.
PS: we mainly use the auth feature of firebase. so i may …
> fix: Unregister socket timeout listener to prevent MaxListenersExceededWarning

- src/messaging/batch-request-internal.ts
- test/unit/messaging/batch-requests.spec.ts
- Increase batch send timeout to 15 seconds
- Extension to: #1947 
Resolves: https://github.com/firebase/firebase-admin-node/issues/1900
> fix(fcm): Increase batch send timeout to 15 seconds

- etc/firebase-admin.api.md
- etc/firebase-admin.machine-learning.api.md
- src/machine-learning/machine-learning-api-client.ts
- src/machine-learning/machine-learning-namespace.ts
- src/machine-learning/machine-learning.ts
Mark AutoML model support as deprecated. A prequel to #1974  
Internal API: go/yiyfd
> change(ml): Deprecate AutoML model support

- src/firestore/firestore-internal.ts
- src/firestore/index.ts
- test/unit/firestore/index.spec.ts
- Fixed a caching issue when a non-empty `FirestoreSettings` object is passed to `initializeFirestore(...)`
- Improved test coverage for `initializeFirestore()`
Before:
```js
initializeFirestore(app)
getFirestore(app) // works!
---
initializeFirestore(app, {})
getFirestore(app) // works!
---
initializeFirestore(app, { preferRest: true })
getFirestore(app) // throws `firestore/failed-precondition` error!
```
Related to: #1901
> fix(firestore): Fix PreferRest caching issue

- src/app/credential-internal.ts
- test/unit/app/credential-internal.spec.ts
- Add more unit tests to cover #1862
> chore: Increase test coverage for service account impersonation support

- docgen/extras/firebase-admin.database.md
Issues here discovered via doc feedback: https://listnr.corp.google.com/report/90770486778
I *think* these may have been broken for a while, since we updated the JS v9 docgen process.
> Fixing links to externally defined RTDB APIs.

- etc/firebase-admin.messaging.api.md
- src/messaging/messaging.ts
1. Deprecate sendAll and sendMulticast
2. Add dummy implementation for sendEach and sendEachForMulticast to avoid errors reported by api-extractor
> Deprecate sendAll and sendMulticast

- src/messaging/messaging-api-request-internal.ts
- src/messaging/messaging.ts
- test/unit/messaging/messaging.spec.ts
`sendEach` vs `sendAll`
1. `sendEach` sends one HTTP request to V1 Send endpoint for each message in the array. `sendAll` sends only one HTTP request to V1 Batch Send endpoint to send all messages in the array.
2. `sendEach` calls `Promise.allSettled` to wait for all `httpClient.send` calls to complete and construct a `BatchResponse`. An `httpClient.send` call to V1 Send endpoint either completes with a success or throws an error. So if an error is thrown out, the error will be caught in `sendEach` and turned into a `SendResponse` with an error. Therefore, unlike `sendAll`, `sendEach` does not always throw an error for a total failure. It can also return a `BatchResponse` with only errors in it.
`sendEachForMulticast` calls `sendEach` under the hood.
> Implement `sendEach` and `sendEachForMulticast`

- test/integration/messaging.spec.ts
Add integration tests: `sendEach()`, `sendEach(500)`, `sendEachForMulticast()`
> Add integration tests for `sendEach` and `sendMulticast`

- test/integration/app-check.spec.ts
- App check tokens are getting additional claims (ex: `jti`) and the current test expects only the given claims to be in the token and fails if there are additional claims.
- Updating the test case to expect "at least" the main claims.
> chore: update app check integration tests

- etc/firebase-admin.messaging.api.md
- src/messaging/messaging-api-request-internal.ts
- src/messaging/messaging.ts
- test/integration/messaging.spec.ts
- test/unit/messaging/messaging.spec.ts
- Deprecate `sendAll()` and `sendMulticast()` APIs.
- Add new `sendEach()` and `sendEachForMulticast()` APIs.
> feat(fcm): Add `sendEach` and `sendEachForMulticast` for FCM batch send

- etc/firebase-admin.api.md
- etc/firebase-admin.app-check.api.md
- src/app-check/app-check-api-client-internal.ts
- src/app-check/app-check-api.ts
- src/app-check/app-check-namespace.ts
- src/app-check/app-check.ts
- src/app-check/index.ts
- test/unit/app-check/app-check-api-client-internal.spec.ts
- test/unit/app-check/app-check.spec.ts
RELEASE NOTE: Added replay protection feature to App Check `verifyToken()` API.
> feat(appcheck): Added replay protection feature to App Check `verifyToken()` API

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- `firebase-tools` (used for emulator tests) has dropped support for Node 14 starting v12.0.0
- Admin SDK still support Node 14 and we run our CIs on the lowest version that we support.
- Installing `firebase-tools@11.30.0` on Github actions to fix the CIs and nightly builds.
> chore: Pin `firebase-tools@11.30.0` to fix the CIs

- etc/firebase-admin.api.md
- etc/firebase-admin.firestore.api.md
- package-lock.json
- src/firestore/firestore-namespace.ts
- src/firestore/index.ts
- test/integration/firestore.spec.ts
Fixes #2191, missing export for `Filter` from Firestore. This builds off of #2167 (and includes @danReynolds as commit co-author) by addressing https://github.com/firebase/firebase-admin-node/pull/2167#issuecomment-1559996747.
Added a test to ensure `Filter` is exported
> fix(firestore): Export `Filter` type from Firestore

- src/auth/auth-api-request.ts
- src/auth/auth-config.ts
- src/auth/tenant.ts
- src/auth/token-verifier.ts
- src/remote-config/remote-config-api-client-internal.ts
> fix Unsafe JavaScript Equality Checking

- package-lock.json
- package.json
- Upgrade Firestore to v6.6.0 to support `FIRESTORE_PREFER_REST` environment variable
> chore: Upgrade Firestore to v6.6.0

- src/auth/user-record.ts
- test/unit/auth/user-record.spec.ts
Adding a `TotpInfo` field to `UserRecord` for Admin users to view a user's MFA configuration. TOTP enrollment for users is enabled via client SDKs only. 
Testing was done by manually enrolling a user on TOTP using curl and creating a test app to get the corresponding user's `UserRecord` configuration
Manual testing output:
```
MultiFactorSettings {
enrolledFactors: [
TotpMultiFactorInfo {
uid: 'bd8fa8e0-194c-443e-82e9-77b39868aed7',
factorId: 'totp',
displayName: 'enroll-totp-test',
enrollmentTime: 'Wed, 31 May 2023 20:39:18 GMT',
totpInfo: {}
}
]
}
```
> feat(auth): Add `TotpInfo` field to `UserRecord`

- test/unit/auth/auth-config.spec.ts
Unnest PasswordPolicyAuthConfig from OIDCConfig
> Fix nesting in auth config tests

- src/utils/api-request.ts
fixes #2235
The socket code was only introduced to fix a bug in NodeJS 12 (https://github.com/firebase/firebase-admin-node/commit/db8be2620a5c9cfc5b9824d9d2487ab9815f5baf) and since then has even needed a patch (https://github.com/firebase/firebase-admin-node/commit/1a34bc49373a5a34bb0efc006ea156d66168103c). However the code does not seem necessary at all anymore. Removing this code resolved the described memory leak.
> fix(auth): Memory Leak in AsyncHttpCall affecting auth.listUsers

- src/auth/user-record.ts
- Added changes from the TW review on #2197
> fix: Update TOTP docstrings

- package-lock.json
- package.json
Reverts firebase/firebase-admin-node#2244
This change was accidentally included in `firebase-admin` `11.10.0`. Reverting to prepare an emergency patch release. `database-compat` upgrade should be included in the next major version of `firebase-admin`
RELEASE NOTES: Fixed an issue which caused the incompatibility in database types in version `11.10.0`
> fix: Revert "chore: upgrade database-compat"

- src/auth/auth-api-request.ts
> Bug Fix for issue #2320

- etc/firebase-admin.storage.api.md
- package-lock.json
- package.json
- src/utils/api-request.ts
- test/unit/index.spec.ts
- Upgraded `@firebase/database-compat` to `v1.0.2` and `@firebase/database-types` to `v1.0.0`
- Upgraded `typescript` to `^5.1.6`
- Upgraded `@types/node` to `^20.10.3`
- Upgraded `@google-cloud/storage` to `^7.7.0`
> build(deps): Bump typescript, database-compat

- src/remote-config/remote-config-api.ts
This is an incremental change to define the API.
Working with @lahirumaramba.
Ran `npm test` and all tests pass.
> Define SSRC API

- src/remote-config/remote-config-api-client-internal.ts
- src/remote-config/remote-config-api.ts
- test/unit/remote-config/remote-config-api-client.spec.ts
Internal client updates.
This is based on PR #2456, which defined the API.
Working with @lahirumaramba and @trekforever.
Ran npm test and all tests pass.
> Update SSRC API client

- docgen/extras/firebase-admin.database.md
- src/database/database-namespace.ts
- src/database/database.ts
- src/database/index.ts
Firebase Admin consumes `@firebase/database-compat` and should reference those docs.
> [chore] Fixed links to rtdb api docs

- etc/firebase-admin.remote-config.api.md
- src/remote-config/remote-config-api.ts
- src/remote-config/remote-config.ts
- test/unit/remote-config/remote-config.spec.ts
In practice, we only set default config using the initialization methods, so make the internal field private to simplify the API.
This wasn't a controversial field in API review.
Tested by running `npm test`.
Makes `defaultConfigs` private.
> Remove defaultConfig from public SSRC API

- etc/firebase-admin.remote-config.api.md
- src/remote-config/index.ts
- src/remote-config/remote-config-api.ts
- src/remote-config/remote-config.ts
It doesn't make sense to pass a cached template to `getServerTemplate` because the method loads a new template immediately.
I see a recommendation to define distinct interfaces for method options: https://github.com/microsoft/tsdoc/issues/19.
So, this change splits `ServerTemplateOptions` into `GetServerTemplateOptions` and `InitServerTemplateOptions`.
Tested with `npm test`.
Splits `ServerTemplateOptions` into `GetServerTemplateOptions` and `InitServerTemplateOptions`.
> Differentiate options for sync and async SSRC initialization

- etc/firebase-admin.remote-config.api.md
- src/remote-config/remote-config-api.ts
- src/remote-config/remote-config.ts
- test/unit/remote-config/remote-config.spec.ts
During testing, we commonly stored a template as JSON. It was then inconvenient to parse that into an object of a specific type (TemplateData) just to accommodate the type expected by the option. 
This change updates `initServerTemplate` to also accept a JSON string, in addition to the existing ServerTemplateData.
Unit tested via npm test
The `InitServerTemplateOptions.template` now accepts a union type `ServerTemplateData|string` instead of just `ServerTemplateData`
> Add functionality to accept a JSON template string when initializing a RC server template

- etc/firebase-admin.remote-config.api.md
- src/remote-config/index.ts
- src/remote-config/remote-config-api.ts
- src/remote-config/remote-config.ts
- test/unit/remote-config/remote-config.spec.ts
Right now, we can set a RC server template via the constructor. Customers, however, would need to update the template multiple times. The current API exposes `template.cache`, but that feels more like an internal detail than an API now.
* Mark `ServerTemplate.cache` as `private`, and should only be used with-in the class
* Add a new `ServerTemplate.set` to allow for setting the template or templateJSON
* Add a `ServerTemplate.toJSON` to return JSON representation (`ServerTemplateData`) of the template
* Update `InitServerTemplate` to make use of the new set method.
Added new unit tests for the new `set` method. Update existing tests to make use of `toJSON()` instead of the cache.
* `ServerTemplate.cache` is now private and cannot be accessed outside of the class
* New …
> Add #set and #toJSON to RC ServerTemplate

- package-lock.json
- package.json
Version 12.1.0 of the Admin SDK added a dependency on a package called farmhash. This package has a dev dependency on python via node-gyp. The node-gyp package on older versions of Node looks for a binary called `python`. This results in `npm install` of the Admin SDK failing if it can't find a binary with that name ("env: python: No such file or directory").
Original error report: https://github.com/lovell/farmhash/issues/47#issuecomment-2060441642
Fortunately, the owner of the farmhash package quickly added a prebuilt binary and released a version 3.3.1: https://github.com/lovell/farmhash/issues/41
So, this PR updates the Admin SDK's package-lock.json to use farmhash version 3.3.1.
Folks can workaround this issue in the meantime by installing Python or aliasing an existing binary.
Steps …
> Update package.json to use farmhash 3.3.1

- etc/firebase-admin.app.api.md
- etc/firebase-admin.auth.api.md
- etc/firebase-admin.database.api.md
- etc/firebase-admin.firestore.api.md
- etc/firebase-admin.installations.api.md
- etc/firebase-admin.instance-id.api.md
- etc/firebase-admin.messaging.api.md
- etc/firebase-admin.project-management.api.md
- src/utils/error.ts
A continuation of #2151 (issue #1666)
> Fix api extractor issues to expose error types

- .github/workflows/ci.yml
- README.md
- test/unit/app/firebase-app.spec.ts
- Deprecate Node.js 16 support
- Add Node.js 18, 20, and 22 to CIs
> change: Deprecate Node.js 16 support

- src/utils/error.ts
> fix: Use optional chaining in FirebaseError

- src/utils/api-request.ts
- test/unit/app-check/app-check-api-client-internal.spec.ts
- test/unit/functions/functions-api-client-internal.spec.ts
- test/unit/machine-learning/machine-learning-api-client.spec.ts
- test/unit/remote-config/remote-config-api-client.spec.ts
- test/unit/security-rules/security-rules-api-client.spec.ts
This PR is intended to fix a current bug in firebase-admin.
Google Cloud recommends utilizing [Application Default Credentials (ADC)] (https://cloud.google.com/docs/authentication/application-default-credentials), however this feature does not fully work with the firebase-admin-node library when you want to utilize a human account (person@domain.com) instead of a service account.
Some GCP APIs require you to specify the quota project associated to the request, however, the current implementation of the firebase-admin-node library does not provide the project ID when making requests to GCP APIs, even if you set them through `gcloud auth application-default set-quota-project YOUR_PROJECT`, because the code that handles the requests never adds the project ID to the request. And you get …
> fix: Make ADC + human account work with firebase-admin

- etc/firebase-admin.remote-config.api.md
- src/remote-config/condition-evaluator-internal.ts
- src/remote-config/index.ts
- src/remote-config/remote-config-api.ts
- test/unit/remote-config/condition-evaluator.spec.ts
Setting up the API interfaces and some evaluation logic for a set of initial operators (just string operatorss for now). Looking for an early review here to just make sure we're all aligned on approach before adding logic for the remaining operators.
> Initial set up and evaluation logic for server side custom signals

- src/remote-config/condition-evaluator-internal.ts
- test/unit/remote-config/condition-evaluator.spec.ts
Address minor bug fixes in numeric version handling
> Ssrc targeting numeric version fixes

- src/app/firebase-app.ts
- test/integration/messaging.spec.ts
- test/unit/app/firebase-app.spec.ts
- Concurrent calls to getToken() don't utilize cache because of a race condition which causes multiple token refreshes.
- Fixing by returning the existing promise to a token if one is still pending instead of requesting a new one.
> fix: `getToken()` returns existing promise to a token if one exists instead of a new token.

- test/integration/messaging.spec.ts
Re-skip broken test originally skipped in #1292
> chore: Skip sendToDeviceGroup integration test

- package-lock.json
- src/functions/functions-api-client-internal.ts
- test/unit/functions/functions-api-client-internal.spec.ts
Depends on: https://github.com/firebase/firebase-tools/pull/7475
Allows the admin SDK to enqueue and delete tasks within the locally running cloud tasks emulator to provide for easier testing. 
Introduces `CLOUD_TASKS_EMULATOR_HOST` which should contain the host of the Cloud Tasks emulator if it is running. When set, the admin SDK will reroute requests from `enqueue` and `delete` to the emulator rather than the production instance.
> Reroute Cloud Tasks to emulator when it is running

- etc/firebase-admin.messaging.api.md
- src/messaging/messaging.ts
- test/integration/messaging.spec.ts
- Mark legacy functions `sendToTopic` and `sendToCondition` as deprecated.
- Remove integration tests for FCM legacy (deprecated) APIs as these APIs will be removed in the upcoming major release.
> chore(fcm): Deprecate sendToTopic and Condition

- CHANGELOG.md
Add a CHANGELOG.md that just points people to the GitHub release notes. Just a convenient way to redirect those who go looking for a CHANGELOG at first.
> Add a CHANGELOG.md that just points people to the GitHub release notes

- src/app-check/token-verifier.ts
- src/utils/jwt.ts
- test/unit/app-check/token-verifier.spec.ts
- test/unit/utils/jwt.spec.ts
Fix: support httpAgent in JwksFetcher https://github.com/firebase/firebase-admin-node/issues/2684
> fix(app-check): support `httpAgent` in `JwksFetcher`

- src/auth/auth-api-request.ts
- test/integration/auth.spec.ts
- test/unit/auth/auth-api-request.spec.ts
- Add missing `Math.floor()` when setting `validDuration` in `createSessionCookie()`
- Modified test to use an `expiresIn` value set to the millisecond to verify this resolves the issue.
> fix(auth): Add missing `Math.floor()` when setting `validDuration` in `createSessionCookie()`

- etc/firebase-admin.auth.api.md
- src/auth/action-code-settings-builder.ts
- src/auth/base-auth.ts
- src/utils/error.ts
- test/unit/auth/action-code-settings-builder.spec.ts
- test/unit/auth/auth-api-request.spec.ts
- test/unit/auth/auth.spec.ts
API proposal - [go/firebaseauth-fdl-deprecation-api-proposal](http://goto.google.com/firebaseauth-fdl-deprecation-api-proposal)
> update actionCodeSetting with linkDomain field

- src/functions/functions-api-client-internal.ts
The docstring for `getFunctions.taskQueue()` advertises that task queues can be referenced by both fully and partially qualified resource names, but a user reported that fully qualified resource names was not working. This PR updates the resource resolution logic to properly resolve to the corresponding task queue in the new Cloud Tasks emulator.
Fixes https://github.com/firebase/firebase-admin-node/issues/2725.
> fix(functions): Allow both partial and full resource names to enqueue tasks in emulator

- etc/firebase-admin.auth.api.md
- src/auth/tenant.ts
- test/unit/auth/tenant.spec.ts
> Remove tenant level mobileLinksConfig CRUD.

- test/integration/data-connect.spec.ts
> chore: fix data connect integration tests

- test/integration/auth.spec.ts
- Remove an accidental `describe.only(...`  tag that went in #2625
> chore: Update auth.spec.ts

- package-lock.json
- package.json
- Pin `@firebase/database-compat` to `v1.0.8`
- Pin `@firebase/database-types` to `v1.0.5`
Fix related to https://github.com/firebase/firebase-js-sdk/issues/8583
RELEASE NOTES: This version pins `@firebase/database-compat` to `v1.0.8` and `@firebase/database-types` to `v1.0.5` to maintain compatibility with Node.js 14 and 16. Node.js 14 and 16 support is deprecated and Node.js 18+ will be required in the next major version.
> fix: Pin `@firebase/database-compat` to `v1.0.8`

- etc/firebase-admin.messaging.api.md
- src/messaging/messaging-api.ts
- src/messaging/messaging-internal.ts
- test/integration/messaging.spec.ts
- test/unit/messaging/messaging.spec.ts
Added the `directBootOk` field to the `AndroidConfig` type.
> feat(fcm): Add directBootOk field to AndroidConfig

- package-lock.json
- package.json
- src/app/credential-internal.ts
- src/functions/functions-api-client-internal.ts
- src/utils/index.ts
- test/integration/data-connect.spec.ts
- test/resources/mocks.ts
- test/unit/app/credential-internal.spec.ts
- test/unit/app/firebase-namespace.spec.ts
- test/unit/app/index.spec.ts
- test/unit/firebase.spec.ts
- test/unit/firestore/firestore.spec.ts
- test/unit/utils/index.spec.ts
- Migrate Application default credentials, Service account credentials, Refresh token credentials, and Compute engine credentials to use `google-auth-library`
Resolves: #1377
> change: Migrate credentials to use google-auth-library

- etc/firebase-admin.api.md
- etc/firebase-admin.app-check.api.md
- etc/firebase-admin.app.api.md
- etc/firebase-admin.auth.api.md
- etc/firebase-admin.data-connect.api.md
- etc/firebase-admin.database.api.md
- etc/firebase-admin.eventarc.api.md
- etc/firebase-admin.extensions.api.md
- etc/firebase-admin.firestore.api.md
- etc/firebase-admin.functions.api.md
- etc/firebase-admin.installations.api.md
- etc/firebase-admin.instance-id.api.md
- etc/firebase-admin.machine-learning.api.md
- etc/firebase-admin.messaging.api.md
- etc/firebase-admin.project-management.api.md
- etc/firebase-admin.remote-config.api.md
- etc/firebase-admin.security-rules.api.md
- etc/firebase-admin.storage.api.md
- package-lock.json
- package.json
Updated the following dependencies
-  "@firebase/database-compat": "^2.0.0"
- "@firebase/database-types": "^1.0.6"
- "@types/node": "^22.8.7"
- "uuid": "^11.0.2"
- "@google-cloud/firestore": "^7.10.0"
- "@google-cloud/storage": "^7.14.0"
- "typescript": "5.5.4"
- "@typescript-eslint/eslint-plugin": "^7.16.1",
- "@typescript-eslint/parser": "^7.16.1",
> chore: Upgrade dependencies

- test/integration/auth.spec.ts
Fix the failing tests from the run https://github.com/firebase/firebase-admin-node/actions/runs/11602269449/job/32306878085?pr=2752
> Fix failing FDL deprecation integration tests

- src/auth/auth-api-request.ts
- src/messaging/messaging-api-request-internal.ts
- src/utils/api-request.ts
- src/utils/index.ts
- test/unit/app-check/app-check-api-client-internal.spec.ts
- test/unit/auth/auth-api-request.spec.ts
- test/unit/data-connect/data-connect-api-client-internal.spec.ts
- test/unit/database/database.spec.ts
- test/unit/eventarc/eventarc.spec.ts
- test/unit/extensions/extensions-api-client-internal.spec.ts
- test/unit/functions/functions-api-client-internal.spec.ts
- test/unit/installations/installations-request-handler.spec.ts
- test/unit/machine-learning/machine-learning-api-client.spec.ts
- test/unit/messaging/messaging.spec.ts
- test/unit/project-management/project-management-api-request.spec.ts
- test/unit/remote-config/remote-config-api-client.spec.ts
- test/unit/security-rules/security-rules-api-client.spec.ts
- test/unit/utils/crypto-signer.spec.ts
Adds headers to all authorized http requests google backend endpoints.
Does not add headers to:
- Firestore
- Storage
- RTDB (database.compact)
> chore: Add `X-Goog-Api-Client` metric header to outgoing authorized http requests

- src/app/credential-internal.ts
- src/utils/api-request.ts
- test/integration/setup.ts
- test/unit/app-check/app-check-api-client-internal.spec.ts
- test/unit/data-connect/data-connect-api-client-internal.spec.ts
- test/unit/extensions/extensions-api-client-internal.spec.ts
- test/unit/functions/functions-api-client-internal.spec.ts
- test/unit/machine-learning/machine-learning-api-client.spec.ts
- test/unit/remote-config/remote-config-api-client.spec.ts
- test/unit/security-rules/security-rules-api-client.spec.ts
- test/unit/utils/api-request.spec.ts
- The quota project id should only be set for Application default credentials with human accounts.
- The SDK will use the quota project id found in credentials (through google-auth-client).
- `GOOGLE_CLOUD_QUOTA_PROJECT` overrides the project id found in credentials.
This PR fixes #2658
> fix: Set the Quota Project ID only for ADC human accounts

- src/app/credential-internal.ts
> fix: Fix the property names when initializing the SDK with the `ServiceAccount` type

- package-lock.json
- package.json
- src/firestore/firestore-internal.ts
- test/unit/firestore/firestore.spec.ts
- Set `firebaseAdminVersion` in Firestore setting to append `fire-admin` tag to `x-goog-api-client`.
- Bump `@google-cloud/firestore` to v7.11.0
This is dependent on https://github.com/googleapis/nodejs-firestore/pull/2238 which is available in `@google-cloud/firestore` v7.11.0 but does not break previous versions.
> chore: Add firebaseAdminVersion to Firestore settings

- src/utils/crypto-signer.ts
- test/unit/utils/crypto-signer.spec.ts
fixes #2800
Instead of passing in an explicit service account name `IAMSigner` now takes in an app instance. This way we can use credentials (Google Auth) instance to get the service account name
> fix(auth): Fix credentials issue in createToken() when using ADC

- test/integration/postcheck/package.json
Update typescript version in the post-check test. We use it to verify the build artifacts in staging.
> chore: Update postcheck typescript version

- src/remote-config/condition-evaluator-internal.ts
- test/unit/remote-config/condition-evaluator.spec.ts
* Make sure all existing tests in the repository pass after your change [Verified all existing tests pass]
* If you fixed a bug or added a feature, add a new test to cover your code [Unit tests added]
Fixes #2793
> fix: equality comparison for semantic version when number of segments = max allowed segments

- etc/firebase-admin.messaging.api.md
- src/messaging/messaging-api.ts
- src/messaging/messaging-internal.ts
- test/integration/messaging.spec.ts
- test/unit/messaging/messaging.spec.ts
> feat(fcm): Support `proxy` field in FCM `AndroidNotification`

- src/utils/api-request.ts
- test/unit/utils/api-request.spec.ts
RELEASE NOTE: Unwrapped aggregated HTTP/2 session errors to surface the sub errors which caused it.
* Unwraps an `AggregateError` and surfaces the sub errors that caused it.
> fix(fcm): Provide sub errors from a session `AggregateError` to remove ambiguity

- etc/firebase-admin.data-connect.api.md
- src/data-connect/data-connect-api-client-internal.ts
- src/data-connect/data-connect.ts
- test/unit/data-connect/data-connect-api-client-internal.spec.ts
- test/unit/data-connect/index.spec.ts
- test/unit/index.spec.ts
Add new API interfaces for `insert`, `insertMany`, `upsert`, `upsertMany` operations.
> feat(fdc): Data Connect Bulk Import
