- npm-shrinkwrap.json
- package.json
> Bumped version to 5.0.1

- src/index.d.ts
> Use intersection not overloading in sendToDevice

- package.json
> Updated repository info

- npm-shrinkwrap.json
- package.json
- src/firebase-app.ts
- src/firebase-namespace.ts
- src/firestore/firestore.ts
- src/firestore/register-firestore.ts
- src/index.d.ts
- src/index.ts
- src/storage/storage.ts
- src/utils/error.ts
- src/utils/index.ts
- test/integration/firestore.js
- test/integration/index.js
- test/integration/typescript/package.json
- test/integration/typescript/src/example.test.ts
- test/integration/typescript/tsconfig.json
- test/resources/mocks.ts
- test/unit/firestore/firestore.spec.ts
- test/unit/index.spec.ts
- test/unit/utils/index.spec.ts
- verifyReleaseTarball.sh
Implementing Firestore integration. API proposal at go/firebase-admin-firestore
Usage:
```
const fs = admin.firestore();
```
> Firestore API

- npm-shrinkwrap.json
- package.json
> Upgraded to Firestore 0.8.1

- npm-shrinkwrap.json
- package.json
- test/integration/firestore.js
Added a test case to check for Doc Ref's
> Upgraded to latest Firestore client

- package-lock.json
- package.json
> Upgraded Firestore dependency to 0.10.0

- package.json
> Removing unused dependency

- package-lock.json
- package.json
> Upgraded Firestore version to 0.10.1

- package-lock.json
- package.json
- test/unit/auth/token-generator.spec.ts
> Upgrading jsonwebtoken library to latest version

- src/auth/token-generator.ts
- test/unit/auth/token-generator.spec.ts
> Add auth/id-token-expired to verifyIdToken expired error message

- CHANGELOG.md
> Initial CHANGELOG.md

- test/integration/instance-id.spec.ts
Fixing the instance id in the integration tests for deletion.
> Fixing the instance id in the integration tests for deletion.

- package-lock.json
- package.json
> Upgraded node-forge to latest available

- src/index.d.ts
Export Query, QuerySnapshot & DocumentData in the `admin.firestore` namespace. I'm unsure if this needs any tests since it's just 3 extra export statements.
> Export Query, DocumentData and QuerySnapshot

- CHANGELOG.md
- package-lock.json
- package.json
- verifyReleaseTarball.sh
Also updating a path in a release script in the process.
> Bumped version to 5.12.1

- test/integration/auth.spec.ts
Changes Auth integration tests for session cookies to use multiple UIDs to minimize the risk of flakiness in integration tests.
> Changes Auth integration tests for session cookies to use multiple UIDs

- src/firebase-namespace.ts
> nit: Fix minor typo environmet

- package-lock.json
- package.json
update firestore version to 0.18.0
> update firestore version to 0.18.0

- src/firestore/firestore.ts
- test/unit/firestore/firestore.spec.ts
pass firebase version to firestore
> pass firebase version to firestore

- CHANGELOG.md
- src/messaging/messaging-api-request.ts
- test/unit/messaging/messaging.spec.ts
already fixed on firebase-admin-go
> fix FcmErrorCode error type

- CHANGELOG.md
- src/index.d.ts
- src/messaging/messaging.ts
- src/utils/validator.ts
- test/unit/messaging/messaging.spec.ts
> Implemented APNs Critical Sound Support

- CHANGELOG.md
- src/auth/user-record.ts
- src/index.d.ts
- test/unit/auth/auth.spec.ts
- test/unit/auth/user-record.spec.ts
Fixes optional fields in UserRecord types to be optional.
References will be updated to reflect that too.
> Fixes optional fields in UserRecord types to be optional.

- CHANGELOG.md
- package-lock.json
- package.json
- test/integration/firestore.spec.ts
Upgraded Firestore and re-generated the package lock file. Also updated the changelog file for both Firestore and GCS.
> Upgraded Cloud Firestore to the latest

- CHANGELOG.md
- src/auth/user-record.ts
- src/index.d.ts
> Improve typings of `UpdateRequest` interface

- src/firebase-namespace.ts
- src/firestore/firestore.ts
> Use only named exports of @google-cloud/firestore

- CONTRIBUTING.md
Minor updates based on DiRT feedback.
> Updated setup instructions

- package-lock.json
- package.json
Fixes some vulnerabilities reported by `npm audit`
> Upgrading some dev dependencies

- package-lock.json
- package.json
This updates `firebase-admin` to use the latest version of `@firebase/app`, which I expect to fix https://github.com/firebase/quickstart-nodejs/issues/76
> Bump firebase dependencies

- src/auth/user-import-builder.ts
- test/unit/auth/user-import-builder.spec.ts
Adds validation for UserImportOptions.
> Adds validation for UserImportOptions.

- docgen/generate-docs.js
Updating script to create links to updated Cloud Firestore reference.
> Updating link for Firestore type aliases.

- package-lock.json
- package.json
It's a sibling PR to https://github.com/firebase/firebase-js-sdk/pull/1916
> make @firebase/app a devDependency

- docgen/content-sources/node/toc.yaml
Adds missing paths of new Auth multi-tenancy data structures to docgen/content-sources/node/toc.yaml.
> Adds missing paths to toc.yaml

- package-lock.json
- test/integration/auth.spec.ts
- test/integration/setup.ts
Fixes invalid SAML and OIDC provider IDs randomly generated in integration tests.
The Auth server enforces the following format: [a-z][A-Za-z0-9_.-]*[A-Za-z0-9]
> Fix broken integration tests due to invalid provider IDs

- src/messaging/messaging-types.ts
- test/unit/messaging/messaging.spec.ts
- Add missing property mappings for imageUrl to image in FCM notifications
- Update unit tests to match property mapping changes
> Add mappings to image in notification

- src/auth/auth-api-request.ts
- src/auth/auth-config.ts
- src/auth/auth.ts
- src/auth/tenant.ts
- src/instance-id/instance-id-request.ts
- src/messaging/messaging.ts
- test/integration/database.spec.ts
- test/integration/setup.ts
- test/unit/auth/action-code-settings-builder.spec.ts
- test/unit/auth/auth-api-request.spec.ts
- test/unit/auth/auth-config.spec.ts
- test/unit/auth/auth.spec.ts
- test/unit/auth/tenant-manager.spec.ts
- test/unit/auth/tenant.spec.ts
- test/unit/auth/user-import-builder.spec.ts
- test/unit/firebase-app.spec.ts
- test/unit/firebase-namespace.spec.ts
- test/unit/firestore/firestore.spec.ts
- tsconfig.json
Also add option to tsconfig.json to prevent re-occurrences.
> Remove unused local variables.

- src/messaging/messaging.ts
> Update messaging.ts: Fixed a typo in a comment

- gulpfile.js
The compilation results of the test files are discarded... the process
is just to allow the typescript compiler to pass over all files at once
(rather than encountering errors one file at a time by running unit
tests.)
> Fix 'gulp watch' command and also allow compilation of test files.

- docgen/content-sources/node/toc.yaml
- Add `LightSettings` to `toc.yaml`
> Add LightSettings interface to docgen

- package-lock.json
- package.json
> Bumped version to 8.7.0

- package-lock.json
- package.json
> Bumped version to 8.8.0

- src/auth/token-generator.ts
- test/unit/auth/token-generator.spec.ts
Requires exposing this constant so that the tests can use it.
> Eliminate duplicate BLACKLISTED_CLAIMS

- package-lock.json
- package.json
RELEASE NOTE: Upgraded the `@firebase/database` dependency to v0.5.17.
> fix(rtdb): Upgraded all @firebase/* dependencies

- package-lock.json
- package.json
> Bumped version to 8.9.0

- test/integration/setup.ts
> Fixing a compilation error in integ tests

- package-lock.json
- package.json
> Bumped version to 8.9.2

- docgen/content-sources/node/toc.yaml
Defines new MFA types in toc.yaml
> Defines new MFA types in toc.yaml

- docgen/content-sources/node/toc.yaml
- package-lock.json
- src/index.d.ts
Defines MultiFactor{Create|Update}Settings interfaces.
> Defines MultiFactor{Create|Update}Settings interfaces.

- CONTRIBUTING.md
Added Firebase ML API requirements to Contributing doc
> Added Firebase ML API requirements to Contributing doc

- package-lock.json
- package.json
- src/database.d.ts
RELEASE NOTE: Upgraded `@firebase/database` dependency to v0.6.0 which provides a new `admin.database.ServerValue.increment()` function.
> fix(rtdb): Upgraded @firebase/database dependency to latest available

- package.json
> [chore] Release 8.11.0

- .github/workflows/release.yml
> Fix typo in release.yml

- package-lock.json
- src/auth.d.ts
- src/auth/user-import-builder.ts
- src/auth/user-record.ts
Fixes https://github.com/firebase/firebase-admin-node/issues/864
RELEASE NOTE: Updated the typings of the `customClaims` attribute on `UserRecord` and `UserImportRecord` interfaces.
> fix(auth): Refines `UserRecord.customClaims` type.

- src/machine-learning/machine-learning-api-client.ts
- src/machine-learning/machine-learning.ts
> Fixed lint

- test/integration/machine-learning.spec.ts
fixing tests with unhandled promises
> fixing tests with unhandled promises

- docgen/content-sources/node/toc.yaml
- Add new RC types `Version`, `ListVersionsOptions`, `RemoteConfigUser`
> Add new RC types in toc.yaml

- docgen/content-sources/node/toc.yaml
> Add another missing RC type to toc.yaml

- package.json
> [chore] Release 8.13.0

- package.json
* Dropped Node 8 support
* Upgraded Firestore and Storage dependencies
> [chore] Release 9.0.0

- src/auth.d.ts
https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth#verifyIdToken
https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth#verifyidtoken
> Fix url fragment

- src/auth.d.ts
- src/auth/multi-factor-internal.ts
- src/auth/multi-factor.ts
- src/auth/user-record-internal.ts
- src/auth/user-record.ts
- test/unit/auth/user-record.spec.ts
I will be progressively doing PRs into `hlazu-modularizing-auth-combined` for the modularization effort. The end-result will be similar to that in #992.
This covers: `UserRecord`
> auth: Add modularization progress for UserRecord (6/N)

- package-lock.json
- src/index.d.ts
- src/machine-learning/machine-learning-api-client.ts
- src/machine-learning/machine-learning.ts
- test/unit/machine-learning/machine-learning-api-client.spec.ts
- test/unit/machine-learning/machine-learning.spec.ts
Added support for Core ML models
> Added support for Core ML models

- gulpfile.js
- src/firebase-namespace-api.ts
- src/firebase-namespace.d.ts
- src/security-rules/index.ts
- src/security-rules/security-rules.ts
* Exposed `admin.securityRules` namespace.
* Exposed `App.securityRules()` method.
> chore(rules): Exposed admin.securiryRules namespace

- gulpfile.js
- src/firebase-namespace-api.ts
- src/firebase-namespace.d.ts
- src/machine-learning/index.ts
- src/machine-learning/machine-learning-api-client.ts
- src/machine-learning/machine-learning.ts
- test/integration/machine-learning.spec.ts
- test/unit/machine-learning/machine-learning-api-client.spec.ts
- test/unit/machine-learning/machine-learning.spec.ts
Part of go/firebase-node-one-source proposal.
* Exposed `admin.machineLearning` namespace and the `App.machineLearning()` method.
> chore(ml): Exposed admin.machineLearning namespace

- package.json
> [chore] Release 9.4.0

- docgen/theme/layouts/default.hbs
Reinstating tag that devsite needs present to suppress machine translation.
> Adding translation-disabling tag to template

- package.json
> [chore] Release 9.4.1

- package-lock.json
- package.json
Upgrading RTDB and Auth dependencies from JS SDK.
Related to #1099 
RELEASE NOTE: Upgraded dependencies `@firebase/database` and `@firebase/database-types` to the latest available versions. This resolves an inconsistency in the published typings of the Database API.
> fix(rtdb): Upgraded JS SDK dependencies

- package.json
> [chore] Release 9.4.2

- .github/ISSUE_TEMPLATE/general-bug-report.md
- Remove delayed response message for holidays
> Remove delayed response message for holidays

- docgen/content-sources/node/toc.yaml
- etc/firebase-admin.api.md
- src/auth/index.ts
- Export `UserProvider` type
- Add `UserProvider` to `toc.yaml`
> (chore): Export UserProvider type and add it to toc.yaml

- package.json
> [chore] Release 9.5.0

- package.json
> [chore] Release 9.6.0

- package-lock.json
- package.json
RELEASE NOTE: Upgraded `@firebase/database` dependency to version 0.10.0. This makes the `startAfter` and `endBefore` query filters available for Admin SDK users.
Resolves #1241
> feat(rtdb): Upgraded RTDB and other @firebase dependencies

- test/unit/storage/storage.spec.ts
> fix: Revert regression introduced in #1257

- .github/dependabot.yml
Enabling automated dependency updates.
> chore: Enabled dependabot

- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
- Update Node.js version to >=10.13.0
- Resolves #1295
> Update supported Node version to 10.13.0v and up

- docgen/content-sources/node/toc.yaml
- Add `OAuthResponseType` (introduced in #1220) to `toc.yaml`
> Add OAuthResponseType to ToC

- package.json
> [chore] Release 9.10.0

- package.json
A few developers have expressed interest in trying out the ESM entrypoints we introduced to this branch. For them I'd like to publish a new alpha.1 release into the exp tag.
> chore: Bumped version to alpha.1

- docgen/content-sources/node/toc.yaml
Add `AppCheckTokenOptions` to `ToC`
> Add AppCheckTokenOptions type to ToC

- src/messaging/index.ts
> Fix typo and formatting in docs

- package.json
> [chore] Release 9.11.0

- .github/ISSUE_TEMPLATE/general-bug-report.md
Adding delayed response message for holidays
> Add delayed response message for holidays

- package.json
> [chore] Release 10.0.2

- package-lock.json
- package.json
- Updated to `"@google-cloud/firestore": "^4.15.1"` and `"@google-cloud/storage": "^5.18.3"`
- Updated to `"@types/minimist": "^1.2.2"`
> chore: Update storage and firestore dependencies

- package.json
> [chore] Release 10.1.0

- package-lock.json
- package.json
- Update `@firebase/database-types` to `0.9.7`
- Update `@firebase/database-compat` to `0.1.8`
> chore: Update database-compat and database-types

- package.json
> [chore] Release 10.2.0

- package-lock.json
- package.json
- src/utils/api-request.ts
- Switch to `@fastify/busboy` to address the issues in `dicer` package.
- Thank you @Uzlopak, @kibertoad!
Fixes #1512, #1718
RELEASE NOTES: Replaced the `dicer` package with `@fastify/busboy` to address the issues in `dicer`.
> fix: Switch to @fastify/busboy

- package-lock.json
- package.json
- Updated `@firebase/database-compat` to `0.2.4`
> chore: Update database dependencies

- package.json
Bumped version to 11.1.0
- Upgraded the @google-cloud/firestore dependency to v6.3.0.
- Upgraded the @google-cloud/storage dependency to v6.5.2.
> [chore] Release 11.1.0

- package.json
> [chore] Release 11.2.0

- etc/firebase-admin.extensions.api.md
- src/extensions/extensions.ts
- src/extensions/index.ts
> Extensions docstring tweaks

- package.json
- Includes the new `extensions` API
> [chore] Release 11.3.0

- package.json
> [chore] Release 11.4.0

- package.json
> [chore] Release 11.4.1

- package.json
> [chore] Release 11.6.0

- package-lock.json
- package.json
- Upgrade `"@fastify/busboy": "^1.2.1"`,
`"@firebase/database-compat": "^0.3.4"`,
`"@firebase/database-types": "^0.10.4"`
- Upgrade  `"@google-cloud/firestore": "^6.5.0"`,
`"@google-cloud/storage": "^6.9.5"`
> chore: Upgrade dependencies in package.json

- package.json
> [chore] Release 11.7.0

- package.json
> [chore] Release 11.8.0

- package.json
> [chore] Release 11.9.0

- package-lock.json
- package.json
Upgrade `@firebase/database-compat"` to `"^1.0.0"`
and `@firebase/database-types": "^1.0.0"`
> chore: upgrade database-compat

- package.json
Includes: 
- https://github.com/firebase/firebase-admin-node/pull/2216
- https://github.com/firebase/firebase-admin-node/pull/2209
- https://github.com/firebase/firebase-admin-node/pull/2036
- https://github.com/firebase/firebase-admin-node/pull/2197
> [chore] Release 11.10.0

- package.json
Includes #2247 
- Fixed an issue which caused the incompatibility in `database` types in version `11.10.0`.
> [chore] Release 11.10.1

- package-lock.json
- package.json
- bump google-cloud/firestore to 6.8.0
> chore(deps): bump google-cloud/firestore to 6.8.0

- package-lock.json
- package.json
- bump google-cloud/firestore to 7.1.0
- bump google-cloud/storage to 7.6.0
These changes will be included in the upcoming Firebase Admin v12 release
Resolves: #2388, #2374
> chore(deps): bump google-cloud/firestore and google-cloud/storage

- CONTRIBUTING.md
Updated the integration test project setup instructions to be more accurate to the current setup flow.
> chore: Update Firebase integration test project setup instructions.

- src/remote-config/remote-config-api.ts
> Fix minor typo

- package.json
Fixes CIs in #2565 
Resolves: https://github.com/firebase/firebase-admin-node/issues/2564
> build(deps): upgrade jwks-rsa

- package.json
> [chore] Release 12.5.0

- src/messaging/batch-request-internal.ts
Request timeout value correction while sending messaging requests in a batch
> Request timeout const name correction

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- README.md
- package-lock.json
- package.json
> change: Update Node support to 18

- package.json
Includes:
- https://github.com/firebase/firebase-admin-node/pull/2756
- https://github.com/firebase/firebase-admin-node/pull/2466
- https://github.com/firebase/firebase-admin-node/pull/2759
- https://github.com/firebase/firebase-admin-node/pull/2760
- https://github.com/firebase/firebase-admin-node/pull/2757
> [chore] Release 13.0.0

- package.json
> [chore] Release 13.0.1

- package.json
> [chore] Release 13.0.2
